package com.amalaei.engineering;
import android.app.Activity;import android.os.Bundle;import android.widget.*;import android.graphics.Typeface;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.View;import android.view.Gravity;import java.math.BigDecimal;
public final class CalculatorActivity extends Activity {
 private final Calculator calculator=new Calculator();private TextView expression,result,baseValue,taxValue,totalValue,status;private Typeface arabic,numbers;private LinearLayout body;private final int INK=0xff222a3b,ACCENT=0xff6654dc;
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 private TextView text(String s,int size,int color,boolean numeric){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setTypeface(numeric?numbers:arabic);t.setGravity(Gravity.CENTER_VERTICAL|Gravity.END);t.setTextDirection(numeric?View.TEXT_DIRECTION_LTR:View.TEXT_DIRECTION_RTL);if(numeric){t.setSingleLine(true);t.setFontFeatureSettings("tnum");}return t;}
 @Override public void onCreate(Bundle state){super.onCreate(state);arabic=Typeface.createFromAsset(getAssets(),"fonts/Cairo.ttf");numbers=Typeface.create("sans-serif-medium",Typeface.NORMAL);if(state!=null)calculator.restore(state.getString("expression",""),state.getBoolean("finished",false));getWindow().setStatusBarColor(0xfff4f5fa);getWindow().setNavigationBarColor(0xfff4f5fa);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);ScrollView scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setBackgroundColor(0xfff4f5fa);scroll.addView(body);setContentView(scroll);body.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(android.os.Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=i.getInsets(android.view.WindowInsets.Type.systemBars());top=bars.top;bottom=bars.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(dp(18),top+dp(12),dp(18),bottom+dp(16));return i;});
 LinearLayout header=new LinearLayout(this);header.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);header.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);titles.addView(text("حاسبة الأسعار",23,INK,false));titles.addView(text("حساب واضح • ضريبة 15%",12,0xff8790a3,false));header.addView(titles,new LinearLayout.LayoutParams(0,-2,1));Button back=key("رجوع", "backscreen");header.addView(back,new LinearLayout.LayoutParams(dp(68),dp(44)));back.setOnClickListener(v->finish());LinearLayout.LayoutParams hl=new LinearLayout.LayoutParams(-1,-2);hl.setMargins(0,0,0,dp(16));body.addView(header,hl);
 LinearLayout screen=new LinearLayout(this);screen.setOrientation(LinearLayout.VERTICAL);screen.setPadding(dp(20),dp(16),dp(20),dp(18));screen.setBackground(shape(0xff20263b,24));body.addView(screen,new LinearLayout.LayoutParams(-1,-2));TextView cap=text("المبلغ قبل الضريبة  ·  SAR",12,0xffb1b9d3,false);screen.addView(cap);expression=text("0",16,0xffb1b9d3,true);expression.setHorizontalScrollBarEnabled(false);screen.addView(expression,new LinearLayout.LayoutParams(-1,dp(28)));result=text("0",46,Color.WHITE,true);result.setAutoSizeTextTypeUniformWithConfiguration(24,46,1,android.util.TypedValue.COMPLEX_UNIT_SP);result.setTextIsSelectable(true);screen.addView(result,new LinearLayout.LayoutParams(-1,dp(68)));
 LinearLayout breakdown=new LinearLayout(this);breakdown.setOrientation(LinearLayout.VERTICAL);breakdown.setPadding(dp(16),dp(10),dp(16),dp(10));breakdown.setBackground(shape(Color.WHITE,20));LinearLayout.LayoutParams bl=new LinearLayout.LayoutParams(-1,-2);bl.setMargins(0,dp(12),0,dp(12));body.addView(breakdown,bl);baseValue=amountRow(breakdown,"قبل الضريبة",false);taxValue=amountRow(breakdown,"الضريبة 15%",false);View divider=new View(this);divider.setBackgroundColor(0xffedf0f5);LinearLayout.LayoutParams dl=new LinearLayout.LayoutParams(-1,dp(1));dl.setMargins(0,dp(7),0,dp(7));breakdown.addView(divider,dl);totalValue=amountRow(breakdown,"الإجمالي شامل الضريبة",true);
 status=text("",12,0xff8992a4,false);status.setMinHeight(dp(25));body.addView(status);row(new String[]{"AC","⌫","±","÷"},new String[]{"C","back","sign","/"});row(new String[]{"7","8","9","×"},new String[]{"7","8","9","*"});row(new String[]{"4","5","6","−"},new String[]{"4","5","6","-"});row(new String[]{"1","2","3","+"},new String[]{"1","2","3","+"});row(new String[]{"0",".","="},new String[]{"0",".","="});Button vat=key("حساب الضريبة 15%","tax");LinearLayout.LayoutParams vl=new LinearLayout.LayoutParams(-1,dp(60));vl.setMargins(dp(3),dp(10),dp(3),dp(8));body.addView(vat,vl);vat.setOnClickListener(v->act("tax"));TextView note=text("أدخل الأسعار قبل الضريبة. الضرب والقسمة أولًا، والتقريب المالي إلى منزلتين.",11,0xff8790a3,false);note.setSingleLine(false);body.addView(note);display();}
 private TextView amountRow(LinearLayout parent,String label,boolean total){LinearLayout row=new LinearLayout(this);row.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);row.setGravity(Gravity.CENTER_VERTICAL);TextView title=text(label,total?13:12,total?0xff167a69:0xff8992a4,false);row.addView(title,new LinearLayout.LayoutParams(0,-1,1));TextView value=text("0.00",total?26:20,total?0xff167a69:INK,true);value.setAutoSizeTextTypeUniformWithConfiguration(13,total?26:20,1,android.util.TypedValue.COMPLEX_UNIT_SP);value.setTextIsSelectable(true);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(dp(156),-1);vp.setMargins(dp(8),0,0,0);row.addView(value,vp);parent.addView(row,new LinearLayout.LayoutParams(-1,dp(total?45:32)));return value;}
 private Button key(String label,String kind){boolean digit=kind.matches("[0-9.]"),primary=kind.equals("="),tax=kind.equals("tax");int color=tax?0xffe3f3ee:primary?ACCENT:digit?Color.WHITE:0xffe9e8f4;Button b=new Button(this);b.setText(label);b.setTextSize(tax?17:kind.equals("backscreen")?13:kind.equals("C")?20:29);b.setTypeface(tax||kind.equals("backscreen")?arabic:numbers);b.setTextColor(primary?Color.WHITE:tax?0xff167a69:digit?INK:ACCENT);b.setAllCaps(false);b.setMinHeight(0);b.setMinimumHeight(0);b.setPadding(dp(4),0,dp(4),0);b.setStateListAnimator(null);b.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x226654dc),shape(color,18),null));b.setContentDescription(kind.equals("back")?"حذف آخر رقم":kind.equals("C")?"مسح العملية":label);return b;}
 private void row(String[] labels,String[] keys){LinearLayout row=new LinearLayout(this);row.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);LinearLayout.LayoutParams rl=new LinearLayout.LayoutParams(-1,dp(64));rl.setMargins(0,dp(4),0,dp(4));body.addView(row,rl);for(int i=0;i<labels.length;i++){String kind=keys[i];Button b=key(labels[i],kind);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,labels.length==3&&kind.equals("0")?2:1);lp.setMargins(dp(3),0,dp(3),0);row.addView(b,lp);b.setOnClickListener(v->act(kind));}}
 private void act(String key){try{calculator.press(key);display();}catch(IllegalArgumentException e){status.setTextColor(0xffbd4a57);status.setText(e.getMessage());}}
 private void display(){String entered=calculator.expression();expression.setText(entered.isEmpty()?"0":entered.replace('*','×').replace('/','÷'));try{BigDecimal value;boolean pending=false;try{value=calculator.value();}catch(IllegalArgumentException incomplete){if(!"أكمل العملية أولًا".equals(incomplete.getMessage()))throw incomplete;String prefix=entered;while(!prefix.isEmpty()&&"+*/-".indexOf(prefix.charAt(prefix.length()-1))>=0)prefix=prefix.substring(0,prefix.length()-1);value=Calculator.evaluate(prefix.isEmpty()?"0":prefix);pending=true;}String digits=Calculator.plain(value);if(digits.length()>24)digits=value.round(new java.math.MathContext(16)).stripTrailingZeros().toPlainString();result.setText(digits);BigDecimal[] values=Calculator.vat(value);baseValue.setText(Calculator.money(values[0]));taxValue.setText(Calculator.money(values[1]));totalValue.setText(Calculator.money(values[2]));status.setTextColor(0xff8992a4);status.setText(pending?"أدخل العدد التالي • القيم المعروضة لآخر تعبير مكتمل":"النتائج بالريال السعودي");}catch(IllegalArgumentException error){result.setText("—");baseValue.setText("—");taxValue.setText("—");totalValue.setText("—");status.setTextColor(0xffbd4a57);status.setText(error.getMessage());}}
 @Override protected void onSaveInstanceState(Bundle state){state.putString("expression",calculator.expression());state.putBoolean("finished",calculator.finished());super.onSaveInstanceState(state);}
}
