package com.amalaei.engineering;

import android.Manifest;
import android.app.Activity;
import android.app.AlertDialog;
import android.app.DatePickerDialog;
import android.app.role.RoleManager;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.content.pm.ShortcutInfo;
import android.content.pm.ShortcutManager;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.Icon;
import android.net.Uri;
import android.os.Bundle;
import android.view.View;
import android.widget.*;
import org.json.JSONObject;
import java.time.LocalDate;
import java.util.ArrayList;

public final class MainActivity extends Activity {
    private final int BLUE=Color.rgb(91,74,202), INK=Color.rgb(35,42,61), MUTED=Color.rgb(125,134,153), BG=Color.rgb(247,248,252), LINE=Color.rgb(231,234,242);
    private String business=AppMode.MODE, tab="clients", search="";
    private int limit=100,requestFilter=0;
    private LinearLayout root, content;
    private Store store;
    private android.graphics.Typeface cairo;
    private boolean ready=false, importing=false;
    private JSONObject postDraft;
    private AlertDialog postDialog;
    private final java.util.Map<String,EditText> postInputs=new java.util.LinkedHashMap<>();
    private Spinner postCategory;
    private int adFilter=0,adLimit=20;
    private final java.util.LinkedHashSet<Long> selectedCalls=new java.util.LinkedHashSet<>();
    @Override public void onCreate(Bundle state){super.onCreate(state);cairo=android.graphics.Typeface.createFromAsset(getAssets(),"fonts/Cairo.ttf");store=new Store(this);if(state!=null){business=AppMode.MODE;tab=state.getString("tab","clients");}ready=true;render();receive(getIntent());if(!getSharedPreferences("settings",0).getBoolean("notificationsSetup19",false)){getSharedPreferences("settings",0).edit().putBoolean("notificationsSetup19",true).apply();enableNotifications();}if(state!=null&&state.containsKey("postDraft"))try{editPost(new JSONObject(state.getString("postDraft")));}catch(Exception ignored){}}
    @Override protected void onNewIntent(Intent intent){super.onNewIntent(intent);setIntent(intent);receive(intent);}
    @Override protected void onSaveInstanceState(Bundle state){if(postDraft!=null){capturePost();state.putString("postDraft",postDraft.toString());}state.putString("business",business);state.putString("tab",tab);super.onSaveInstanceState(state);}
    @Override protected void onResume(){super.onResume();if(ready){render();Reminders.schedule(this);if(getSharedPreferences("settings",0).getBoolean("autoSync",false)&&checkSelfPermission(Manifest.permission.READ_CALL_LOG)==PackageManager.PERMISSION_GRANTED&&System.currentTimeMillis()-getSharedPreferences("settings",0).getLong("lastSync",0)>60000)syncHistory(false);}}
    @Override protected void onDestroy(){store.close();super.onDestroy();}
    private int dp(int value){return (int)(value*getResources().getDisplayMetrics().density);}
    private GradientDrawable surface(int color){return shape(color,20,0);}
    private GradientDrawable shape(int color,int radius,int stroke){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));if(stroke!=0)d.setStroke(dp(1),stroke);return d;}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(android.view.Gravity.CENTER_VERTICAL);return l;}
    private TextView text(String value,int size){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(INK);t.setTypeface(cairo);t.setFontVariationSettings("'wght' "+(size>=19?650:450));t.setFontFeatureSettings("kern");t.setGravity(android.view.Gravity.START);t.setPadding(0,dp(4),0,dp(4));return t;}
    private void muted(LinearLayout parent,String label){TextView t=text(label,13);t.setTextColor(MUTED);parent.addView(t);}
    private Button button(LinearLayout parent,String label,Runnable action){Button b=new Button(this);b.setText(label);b.setTextSize(14);b.setTypeface(cairo);b.setFontVariationSettings("'wght' 600");b.setAllCaps(false);b.setTextColor(BLUE);b.setMinHeight(0);b.setMinimumHeight(0);b.setPadding(dp(12),dp(8),dp(12),dp(8));b.setStateListAnimator(null);b.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x225B4ACA),shape(0xFFF1EEFC,13,0),null));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(46));lp.setMargins(0,dp(5),0,dp(5));parent.addView(b,lp);b.setOnClickListener(v->action.run());return b;}
    private void primary(Button b){b.setTextColor(Color.WHITE);b.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x33FFFFFF),shape(BLUE,14,0),null));}
    private void alert(String value){new AlertDialog.Builder(this).setMessage(value).setPositiveButton("حسنًا",null).show();}
    private Spinner spinner(LinearLayout parent,String label,String[] values,int selected){muted(parent,label);Spinner sp=new Spinner(this);sp.setPadding(dp(12),dp(6),dp(12),dp(6));sp.setBackground(shape(BG,12,LINE));sp.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,values));sp.setSelection(selected);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(52));lp.setMargins(0,0,0,dp(12));parent.addView(sp,lp);return sp;}
    private LinearLayout card(LinearLayout parent){LinearLayout box=column();box.setPadding(dp(16),dp(14),dp(16),dp(14));box.setBackground(shape(Color.WHITE,20,LINE));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(7),0,dp(7));parent.addView(box,lp);return box;}
    private TextView pill(String label,int ink,int background){TextView t=text(label,11);t.setTextColor(ink);t.setPadding(dp(10),dp(5),dp(10),dp(5));t.setBackground(shape(background,20,0));return t;}
    private void empty(String title,String detail){LinearLayout box=card(content);box.setGravity(android.view.Gravity.CENTER);box.setPadding(dp(24),dp(35),dp(24),dp(35));Glyph icon=new Glyph(this,"clients",BLUE);box.addView(icon,new LinearLayout.LayoutParams(dp(42),dp(42)));TextView t=text(title,19);t.setGravity(17);box.addView(t);TextView d=text(detail,14);d.setTextColor(MUTED);d.setGravity(17);box.addView(d);}
    private void metric(LinearLayout parent,String label,int value,int color){LinearLayout box=column();box.setPadding(dp(12),dp(12),dp(12),dp(12));box.setBackground(shape(Color.WHITE,16,LINE));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(3),0,dp(3),0);parent.addView(box,lp);TextView number=text(String.valueOf(value),25);number.setTextColor(color);box.addView(number);muted(box,label);}
    private String[] stages(String activity){return SurveyRequests.stages(activity,"sales");}
    private String[] stages(String activity,String requestType){return SurveyRequests.stages(activity,requestType);}
    private void enableNotifications(){getSharedPreferences("settings",0).edit().putBoolean("reminders",true).apply();Reminders.channel(this);if(android.os.Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},13);return;}if(!Reminders.allowed(this)){startActivity(Reminders.settings(this));return;}Reminders.deliver(this);Reminders.schedule(this);render();}

    private void render(){
        getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(Color.WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
        root=column();root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.setBackgroundColor(BG);
        root.setOnApplyWindowInsetsListener((v,insets)->{int top,bottom;if(android.os.Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=insets.getInsets(android.view.WindowInsets.Type.systemBars());top=bars.top;bottom=bars.bottom;}else{top=insets.getSystemWindowInsetTop();bottom=insets.getSystemWindowInsetBottom();}v.setPadding(0,top,0,bottom);return insets;});setContentView(root);
        LinearLayout header=row();header.setPadding(dp(20),dp(12),dp(20),dp(12));root.addView(header);
        TextView logo=text(AppMode.LABEL,24);logo.setTextColor(BLUE);header.addView(logo,new LinearLayout.LayoutParams(0,-2,1));TextView local=pill("محفوظ على جهازك",0xFF358876,0xFFEAF5F0);header.addView(local);
        LinearLayout segments=row();segments.setPadding(dp(4),dp(4),dp(4),dp(4));segments.setBackground(shape(0xFFEBEDF4,16,0));LinearLayout.LayoutParams sl=new LinearLayout.LayoutParams(-1,dp(52));sl.setMargins(dp(20),0,dp(20),dp(10));root.addView(segments,sl);
        String[][] activities={{AppMode.MODE,AppMode.LABEL}};for(String[] item:activities){TextView t=text(item[1],13);t.setGravity(17);t.setTextColor(business.equals(item[0])?BLUE:MUTED);if(business.equals(item[0]))t.setBackground(shape(Color.WHITE,12,0));segments.addView(t,new LinearLayout.LayoutParams(0,-1,1));t.setOnClickListener(v->{business=item[0];search="";limit=100;requestFilter=0;render();});}
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);scroll.setVerticalScrollBarEnabled(false);content=column();content.setPadding(dp(20),dp(4),dp(20),dp(20));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        try{if(tab.equals("messages"))messages();else if(tab.equals("settings"))settings();else if(tab.equals("ads"))advertising();else clients();}catch(Exception e){empty("تعذر عرض البيانات","أعد فتح التطبيق وتحقق من مساحة الهاتف.");}
        LinearLayout nav=row();nav.setPadding(dp(6),dp(8),dp(6),dp(4));nav.setBackground(shape(Color.WHITE,0,LINE));root.addView(nav);
        String[][] routes={{"clients","العملاء"},{"today","المتابعات"},{"unassigned","الوارد"},{"messages","الرسائل"},{"ads","الدعاية"},{"settings","الإعدادات"}};
        for(String[] route:routes){boolean active=tab.equals(route[0]);LinearLayout item=column();item.setGravity(17);item.setPadding(0,dp(4),0,dp(4));if(active)item.setBackground(shape(0xFFF1EEFC,14,0));nav.addView(item,new LinearLayout.LayoutParams(0,dp(62),1));item.addView(new Glyph(this,route[0],active?BLUE:MUTED),new LinearLayout.LayoutParams(dp(23),dp(23)));TextView name=text(route[1],10);name.setTextColor(active?BLUE:MUTED);name.setGravity(17);item.addView(name);item.setOnClickListener(v->{tab=route[0];limit=100;render();});}
    }
    private void clients(){
        button(content,"الحاسبة • ضريبة 15%",()->startActivity(new Intent(this,CalculatorActivity.class)));
        String countSql="SELECT COUNT(*) AS total, SUM(CASE WHEN stage<4 THEN 1 ELSE 0 END) AS active, SUM(CASE WHEN stage=4 THEN 1 ELSE 0 END) AS won FROM leads WHERE business=?";ArrayList<JSONObject> stats=business.equals("survey")&&!tab.equals("unassigned")&&requestFilter>0?store.query(countSql+" AND requestType=?",business,SurveyRequests.KEYS[requestFilter-1]):store.query(countSql,business);
        JSONObject counts=stats.get(0);
        content.addView(text(tab.equals("today")?"متابعاتك اليوم":tab.equals("unassigned")?"العملاء الواردون":"علاقات أفضل، فرص أكثر",24));
        muted(content,tab.equals("today")?"كل موعد مهم، وكل متابعة تصنع فرقًا":tab.equals("unassigned")?"عيّن النشاط المناسب للأرقام المستوردة":"نظّم عملاءك وتابع تقدم فرصك في مكان واحد");
        LinearLayout metrics=row();LinearLayout.LayoutParams ml=new LinearLayout.LayoutParams(-1,-2);ml.setMargins(0,dp(14),0,dp(12));content.addView(metrics,ml);metric(metrics,"إجمالي العملاء",counts.optInt("total"),BLUE);metric(metrics,business.equals("survey")?"طلبات نشطة":"فرص نشطة",counts.optInt("active"),0xFFD69538);metric(metrics,"مكتملون",counts.optInt("won"),0xFF348C76);
        if(business.equals("software"))button(content,"اشتراكات ومشاريع ودعم البرامج",()->startActivity(new Intent(this,SoftwareActivity.class)));
        if(business.equals("survey")&&tab.equals("clients"))button(content,"عروض أسعار المساحة • إنشاء PDF",()->startActivity(new Intent(this,QuoteActivity.class)));
        primary(button(content,"+  إضافة عميل جديد",()->edit(new JSONObject(),0)));
        if(tab.equals("today")&&(!Reminders.enabled(this)||!Reminders.allowed(this)))primary(button(content,"تفعيل إشعارات المتابعة",this::enableNotifications));
        if(business.equals("survey")&&!tab.equals("unassigned")){Spinner filter=spinner(content,"نوع الطلب",new String[]{"جميع الطلبات","المبيعات","الدعم الفني","الصيانة","المعايرة"},requestFilter);filter.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){if(pos!=requestFilter){requestFilter=pos;limit=100;render();}}});}
        if(tab.equals("unassigned")){primary(button(content,"إعداد المكالمات والاستيراد بخطوة واحدة",this::callSetup));button(content,"تعيين النشاط للعملاء المحددين",this::assignCalls);}
        if(tab.equals("clients")){
            LinearLayout searchRow=row();LinearLayout.LayoutParams sr=new LinearLayout.LayoutParams(-1,-2);sr.setMargins(0,dp(10),0,dp(10));content.addView(searchRow,sr);EditText find=new EditText(this);find.setTextSize(14);find.setTypeface(cairo);find.setSingleLine(true);find.setHint("ابحث بالاسم أو الرقم أو الشركة");find.setHintTextColor(MUTED);find.setPadding(dp(14),0,dp(14),0);find.setBackground(shape(Color.WHITE,14,LINE));find.setText(search);searchRow.addView(find,new LinearLayout.LayoutParams(0,dp(48),1));Button go=button(searchRow,"بحث",()->{search=find.getText().toString().trim();limit=100;render();});LinearLayout.LayoutParams gl=new LinearLayout.LayoutParams(dp(64),dp(48));gl.setMargins(0,0,dp(8),0);go.setLayoutParams(gl);find.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);find.setOnEditorActionListener((t,id,event)->{if(id==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){go.performClick();return true;}return false;});
        }
        String where="business=?", order="stage ASC, name COLLATE NOCASE";ArrayList<String> args=new ArrayList<>();args.add(business);
        if(tab.equals("today")){where+=" AND stage<4 AND (followUp='' OR followUp<=?)";args.add(LocalDate.now().toString());order="CASE WHEN followUp='' THEN 1 ELSE 0 END, followUp ASC";content.addView(text("المتأخر، ثم المستحق اليوم، ثم العملاء دون موعد. لا تظهر الطلبات المكتملة أو المغلقة.",14));}
        if(tab.equals("unassigned")){where="business=''";args.clear();order="lastCallAt DESC";content.addView(text("اختر النشاط الصحيح لكل عميل مستورد؛ لن يدخل إحصاءات أي نشاط حتى تعيّنه.",16));}
        if(business.equals("survey")&&!tab.equals("unassigned")&&requestFilter>0){where+=" AND requestType=?";args.add(SurveyRequests.KEYS[requestFilter-1]);}
        if(!search.isEmpty()&&tab.equals("clients")){where+=" AND (name LIKE ? OR phone LIKE ? OR company LIKE ?)";for(int i=0;i<3;i++)args.add("%"+search+"%");}
        ArrayList<JSONObject> list=store.query("SELECT * FROM leads WHERE "+where+" ORDER BY "+order+" LIMIT "+(limit+1),args.toArray(new String[0]));
        if(list.isEmpty())empty(tab.equals("today")?"متابعاتك تحت السيطرة":"ابدأ بأول عميل",tab.equals("today")?"لا توجد متابعات مستحقة في هذا النشاط اليوم":"أضف عميلًا أو استورد أرقام المكالمات من الإعدادات");
        if(tab.equals("unassigned")&&!list.isEmpty())button(content,"تحديد المعروض بالكامل",()->{for(int i=0;i<Math.min(limit,list.size());i++)selectedCalls.add(list.get(i).optLong("id"));render();});
        int shown=0,lastStage=-1;for(JSONObject lead:list){if(shown++>=limit)break;if(tab.equals("clients")&&lastStage!=lead.optInt("stage")){lastStage=lead.optInt("stage");String[] groups=business.equals("survey")?(requestFilter==0?SurveyRequests.combined():stages(business,SurveyRequests.KEYS[requestFilter-1])):stages(business);content.addView(text(groups[lastStage],21));}leadCard(lead);}
        if(list.size()>limit)button(content,"عرض المزيد",()->{limit+=100;render();});
    }
    private void leadCard(JSONObject lead){
        LinearLayout box=card(content);if(tab.equals("unassigned")){CheckBox selected=new CheckBox(this);selected.setText("تحديد للتعيين الجماعي");selected.setChecked(selectedCalls.contains(lead.optLong("id")));selected.setOnCheckedChangeListener((v,on)->{if(on)selectedCalls.add(lead.optLong("id"));else selectedCalls.remove(lead.optLong("id"));});box.addView(selected);}
        LinearLayout heading=row();box.addView(heading);String name=lead.optString("name");TextView avatar=text(name.isEmpty()?"؟":name.substring(0,1),22);avatar.setTextColor(BLUE);avatar.setGravity(17);avatar.setPadding(0,0,0,0);avatar.setBackground(shape(0xFFF1EEFC,15,0));heading.addView(avatar,new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout identity=column();identity.setPadding(dp(12),0,dp(12),0);heading.addView(identity,new LinearLayout.LayoutParams(0,-2,1));identity.addView(text(name,18));String phone=lead.optString("phone","");if(!phone.isEmpty()&&!phone.equals("null")){TextView number=text(phone,13);number.setTextDirection(View.TEXT_DIRECTION_LTR);number.setTextColor(MUTED);identity.addView(number);}
        if(lead.optString("business").equals("survey"))muted(box,"نوع الطلب: "+SurveyRequests.label(lead.optString("requestType","sales")));String[] phase=stages(lead.optString("business"),lead.optString("requestType","sales"));int stage=Math.max(0,Math.min(5,lead.optInt("stage")));TextView badge=pill(lead.optString("business").isEmpty()?"غير مصنف":phase[stage],stage==4?0xFF348C76:BLUE,stage==4?0xFFEAF5F0:0xFFF1EEFC);LinearLayout.LayoutParams bl=new LinearLayout.LayoutParams(-2,-2);bl.setMargins(0,dp(12),0,dp(6));box.addView(badge,bl);
        if(!lead.optString("company").isEmpty())muted(box,lead.optString("company"));if(!lead.optString("interest").isEmpty())box.addView(text(lead.optString("interest"),14));
        String due=lead.optString("followUp"),today=LocalDate.now().toString();String label=due.isEmpty()?"لم يحدد موعد متابعة":due.compareTo(today)<0?"متأخرة  •  "+due:due.equals(today)?"متابعة اليوم":"المتابعة  •  "+due;if(!due.isEmpty())label+="  "+lead.optString("followTime","09:00");TextView date=text(label,13);date.setTextColor(!due.isEmpty()&&due.compareTo(today)<=0?0xFFB86F34:MUTED);box.addView(date);
        if(!lead.optString("contactName").isEmpty())muted(box,"جهة الاتصال: "+lead.optString("contactName"));if(lead.optLong("lastCallAt")>0)muted(box,"آخر اتصال: "+android.text.format.DateFormat.format("yyyy-MM-dd HH:mm",lead.optLong("lastCallAt")));
        if(!phone.isEmpty()&&!phone.equals("null"))button(box,"حفظ في جهات اتصال الهاتف",()->savePhoneContact(lead));
        button(box,"سجل التعاملات",()->timeline(lead.optLong("id")));
        LinearLayout actions=row();box.addView(actions);Button edit=button(actions,"التفاصيل",()->edit(lead,0));edit.setLayoutParams(new LinearLayout.LayoutParams(0,dp(44),1));
        if(!phone.isEmpty()&&!phone.equals("null")){Button call=button(actions,"اتصال",()->{store.event(lead.optLong("id"),"dial","فتح شاشة الاتصال — لا يعني إتمام المكالمة",System.currentTimeMillis(),null);startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone)));});LinearLayout.LayoutParams cl=new LinearLayout.LayoutParams(0,dp(44),1);cl.setMargins(dp(6),0,dp(6),0);call.setLayoutParams(cl);Button wa=button(actions,"واتساب",()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+phone.replace("+",""))));}catch(Exception e){alert("لا يوجد تطبيق يستطيع فتح واتساب.");}});wa.setTextColor(0xFF348C76);wa.setBackground(shape(0xFFEAF5F0,13,0));wa.setLayoutParams(new LinearLayout.LayoutParams(0,dp(44),1));}
    }
    private void savePhoneContact(JSONObject lead){String phone=Analysis.phone(lead.optString("phone"));if(phone.isEmpty()){alert("أضف رقم هاتف صحيحًا للعميل أولًا");return;}Boolean exists=PhoneData.exists(this,phone);if(Boolean.TRUE.equals(exists)){alert("هذا الرقم موجود بالفعل في جهات اتصال الهاتف");return;}try{Intent intent=new Intent(exists==null?Intent.ACTION_INSERT_OR_EDIT:Intent.ACTION_INSERT).setType(exists==null?android.provider.ContactsContract.Contacts.CONTENT_ITEM_TYPE:android.provider.ContactsContract.Contacts.CONTENT_TYPE).putExtra(android.provider.ContactsContract.Intents.Insert.NAME,lead.optString("name")).putExtra(android.provider.ContactsContract.Intents.Insert.PHONE,phone).putExtra(android.provider.ContactsContract.Intents.Insert.PHONE_TYPE,phone.startsWith("+9665")?android.provider.ContactsContract.CommonDataKinds.Phone.TYPE_MOBILE:android.provider.ContactsContract.CommonDataKinds.Phone.TYPE_WORK).putExtra(android.provider.ContactsContract.Intents.Insert.COMPANY,lead.optString("company")).putExtra(android.provider.ContactsContract.Intents.Insert.EMAIL,lead.optString("email"));startActivity(intent);}catch(Exception unavailable){alert("تعذر فتح شاشة جهات الاتصال على الهاتف");}}
        private void tools(LinearLayout form,JSONObject lead,AlertDialog parent){
        form.addView(text("ملف العميل",20));
        if(!lead.optString("phone").isEmpty()&&!lead.optString("phone").equals("null"))button(form,"حفظ في جهات اتصال الهاتف",()->savePhoneContact(lead));
        if(lead.optString("business").equals("software"))button(form,"اشتراكات وطلبات هذا العميل",()->startActivity(new Intent(this,SoftwareActivity.class).putExtra("leadId",lead.optLong("id"))));
        button(form,"سجل التعاملات والملاحظات",()->timeline(lead.optLong("id")));
        button(form,"تفاصيل طلب العميل",()->requestDetails(lead.optLong("id")));
        button(form,"قوالب رسائل واتساب",()->templates(lead.optLong("id")));
        if(!lead.optString("followUp").isEmpty()){
            button(form,"تمت المتابعة",()->{parent.dismiss();followAction(lead.optLong("id"),false);});
            button(form,"تأجيل المتابعة إلى الغد",()->{parent.dismiss();followAction(lead.optLong("id"),true);});
        }
        muted(form,"هذه الإجراءات تخص البيانات المحفوظة؛ احفظ تعديلات النموذج أولًا.");
    }
    private EditText field(LinearLayout form,String label,String value,int type){muted(form,label);EditText e=new EditText(this);e.setTextSize(15);e.setTypeface(cairo);e.setTextColor(INK);e.setInputType(type);e.setText(value.equals("null")?"":value);e.setPadding(dp(14),dp(10),dp(14),dp(10));e.setBackground(shape(BG,12,LINE));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(14));e.setMinHeight(dp(50));form.addView(e,lp);return e;}
    private void edit(JSONObject original,long messageId){
        try{
            JSONObject seed=new JSONObject(original.toString());if(!seed.has("id")&&!seed.has("business"))seed.put("business",AppMode.MODE);
            LinearLayout form=column();form.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);form.setPadding(dp(18),dp(8),dp(18),dp(8));ScrollView scroll=new ScrollView(this);scroll.addView(form);
            if(messageId>0)form.addView(text("اقتراحات من النص — راجع الاسم والرقم والنشاط والموعد قبل الحفظ. التحليل محلي بالكلمات والصيغ، وقد لا يفهم السياق.",16));
            EditText name=field(form,"اسم العميل *",seed.optString("name"),1);
            EditText phone=field(form,"الرقم السعودي",seed.optString("phone"),android.text.InputType.TYPE_CLASS_PHONE);phone.setTextDirection(View.TEXT_DIRECTION_LTR);
            Spinner activity=spinner(form,"النشاط",new String[]{"لم يحدد بعد","أجهزة المساحة","البرامج والتطبيقات"},seed.optString("business").equals("survey")?1:seed.optString("business").equals("software")?2:0);
            muted(form,"نوع الطلب التالي خاص بالمساحة. عند تغيير النوع تبدأ المرحلة من جديد؛ اختر المرحلة المناسبة قبل الحفظ.");
            Spinner requestType=spinner(form,"نوع الطلب الحالي — نشاط المساحة",SurveyRequests.LABELS,SurveyRequests.index(seed.optString("requestType","sales")));
            activity.setSelection(AppMode.MODE.equals("survey")?1:2);activity.setEnabled(false);
            Spinner stage=spinner(form,"المرحلة",stages(seed.optString("business"),seed.optString("requestType","sales")),seed.optInt("stage"));
            final String[] previous={seed.optString("business")+":"+seed.optString("requestType","sales")};
            Runnable updateStages=()->{boolean surveying=activity.getSelectedItemPosition()==1;requestType.setEnabled(surveying);String active=activity.getSelectedItemPosition()==2?"software":surveying?"survey":"",kind=surveying?SurveyRequests.KEYS[requestType.getSelectedItemPosition()]:"sales",key=active+":"+kind;if(!key.equals(previous[0])){stage.setAdapter(new ArrayAdapter<String>(MainActivity.this,android.R.layout.simple_spinner_dropdown_item,stages(active,kind)));stage.setSelection(0);previous[0]=key;}};
            AdapterView.OnItemSelectedListener selection=new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int position,long id){updateStages.run();}};activity.setOnItemSelectedListener(selection);requestType.setOnItemSelectedListener(selection);
            EditText company=field(form,"الشركة",seed.optString("company"),1),email=field(form,"البريد الإلكتروني",seed.optString("email"),android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS),interest=field(form,"الجهاز / البرنامج / الخدمة المطلوبة",seed.optString("interest"),1);
            EditText due=field(form,"موعد المتابعة (YYYY-MM-DD)",seed.optString("followUp"),1);due.setTextDirection(View.TEXT_DIRECTION_LTR);
            EditText time=field(form,"وقت التنبيه (HH:mm)",seed.optString("followTime","09:00"),1);time.setTextDirection(View.TEXT_DIRECTION_LTR);
            button(form,"اختيار الوقت",()->{java.time.LocalTime t;try{t=java.time.LocalTime.parse(time.getText());}catch(Exception e){t=java.time.LocalTime.of(9,0);}new android.app.TimePickerDialog(this,(v,h,m)->time.setText(String.format(java.util.Locale.US,"%02d:%02d",h,m)),t.getHour(),t.getMinute(),true).show();});
            button(form,"اختيار موعد",()->{LocalDate now=LocalDate.now();new DatePickerDialog(this,(v,y,m,d)->due.setText(LocalDate.of(y,m+1,d).toString()),now.getYear(),now.getMonthValue()-1,now.getDayOfMonth()).show();});
            button(form,"إزالة الموعد",()->due.setText(""));
            EditText notes=field(form,"ملاحظات",seed.optString("notes"),android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);notes.setMinLines(3);
            CheckBox phoneContact=new CheckBox(this);phoneContact.setTypeface(cairo);phoneContact.setText("فتح جهات اتصال الهاتف لحفظ العميل بعد حفظ بياناته");form.addView(phoneContact);
            AlertDialog dialog=new AlertDialog.Builder(this).setTitle(messageId>0?"مراجعة وحفظ معلومات الرسالة":seed.optLong("id")>0?"تعديل العميل":"عميل جديد").setView(scroll).setPositiveButton("حفظ",null).setNegativeButton("إلغاء",null).create();
            if(seed.optLong("id")>0)tools(form,seed,dialog);
            if(seed.optLong("id")>0)button(form,"حذف العميل",()->new AlertDialog.Builder(this).setMessage("حذف العميل نهائيًا؟ ستبقى الرسائل الأصلية في أرشيف الرسائل.").setNegativeButton("إلغاء",null).setPositiveButton("حذف",(d,w)->{store.remove(seed.optLong("id"));dialog.dismiss();render();Reminders.schedule(this);}).show());
            dialog.setOnShowListener(d->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{
                seed.put("name",name.getText().toString()).put("phone",phone.getText().toString()).put("business",activity.getSelectedItemPosition()==1?"survey":activity.getSelectedItemPosition()==2?"software":"").put("stage",stage.getSelectedItemPosition()).put("requestType",activity.getSelectedItemPosition()==1?SurveyRequests.KEYS[requestType.getSelectedItemPosition()]:"sales").put("company",company.getText().toString()).put("email",email.getText().toString()).put("interest",interest.getText().toString()).put("followUp",due.getText().toString()).put("notes",notes.getText().toString()).put("followTime",time.getText().toString());
                android.database.sqlite.SQLiteDatabase db=store.getWritableDatabase();db.beginTransaction();try{long id=store.save(seed);if(messageId>0)store.reviewed(messageId,id);getSystemService(android.app.NotificationManager.class).cancel("lead",(int)id);db.setTransactionSuccessful();}finally{db.endTransaction();}
                dialog.dismiss();render();Reminders.schedule(this);if(phoneContact.isChecked())savePhoneContact(seed);
            }catch(android.database.sqlite.SQLiteConstraintException duplicate){alert("هذا الرقم موجود بالفعل. اربط الرسالة بالعميل الموجود أو عدّل سجله.");}catch(Exception e){alert(e.getMessage()==null?"تعذر الحفظ":e.getMessage());}}));dialog.show();dialog.getWindow().setBackgroundDrawable(shape(Color.WHITE,24,0));dialog.getWindow().setLayout(-1,-1);dialog.getButton(AlertDialog.BUTTON_POSITIVE).setTextColor(BLUE);dialog.getButton(AlertDialog.BUTTON_NEGATIVE).setTextColor(MUTED);
        }catch(Exception e){alert("تعذر فتح بيانات العميل");}
    }
    private void messages(){
        content.addView(text("رسائل تحتاج المراجعة",23));content.addView(text("شارك نص الرسالة إلى التطبيق للمراجعة؛ لا نقرأ الإشعارات أو المحادثات مباشرة ولا نحلل الصوت والصور.",15));
        primary(button(content,"لصق نص أو محادثة للتحليل",this::pasteText));
        ArrayList<JSONObject> items=store.query("SELECT * FROM messages WHERE state='pending' ORDER BY at DESC LIMIT "+(limit+1));
        if(items.isEmpty())empty("لا توجد رسائل معلّقة","شارك نص رسالة أو ملف TXT من واتساب إلى عملائي، ثم راجع المعلومات قبل حفظها.");
        int shown=0;for(JSONObject message:items){if(shown++>=limit)break;LinearLayout card=card(content);
            card.addView(text(message.optString("sender").isEmpty()?"نص مشارك":message.optString("sender"),19));card.addView(text(message.optString("source")+" • "+android.text.format.DateFormat.format("yyyy-MM-dd HH:mm",message.optLong("at")),14));
            String body=message.optString("body");card.addView(text(body.length()>4000?body.substring(0,4000)+"\n… نص طويل؛ محفوظ في الأرشيف المحلي":body,16));
            button(card,"تحليل ومراجعة المعلومات",()->review(message));button(card,"تجاهل هذه الرسالة",()->new AlertDialog.Builder(this).setMessage("حذف هذه الرسالة من قائمة المراجعة؟").setNegativeButton("إلغاء",null).setPositiveButton("حذف",(d,w)->{store.dismiss(message.optLong("id"));render();}).show());
        }if(items.size()>limit)button(content,"عرض المزيد",()->{limit+=100;render();});
        button(content,"عرض أرشيف الرسائل المراجعة",()->{ArrayList<JSONObject> list=store.query("SELECT sender, body FROM messages WHERE state='reviewed' ORDER BY at DESC LIMIT 50");StringBuilder text=new StringBuilder();for(JSONObject m:list)text.append(m.optString("sender")).append(": ").append(m.optString("body")).append("\n\n");alert(text.length()==0?"لا يوجد أرشيف بعد":text.toString());});
    }
    private void review(JSONObject message){
        String body=message.optString("body");java.util.LinkedHashMap<String,ArrayList<ChatText.Message>> parsed=ChatText.parse(body,message.optLong("at"),false);
        if(parsed.isEmpty()){chooseQuick(message,Analysis.inspect(body,message.optLong("at")),"");return;}
        LinearLayout f=form();muted(f,"اختر مرسل رسائل العميل حتى لا تُخلط رسائلك أو رسائل المجموعة بمعلوماته. لا تعتمد على عنوان الملف لتحديد الهوية.");String[] people=parsed.keySet().toArray(new String[0]);Spinner sender=spinner(f,"صاحب الرسائل المطلوب تحليلها",people,0);Spinner dates=spinner(f,"صيغة تاريخ ملف واتساب",new String[]{"يوم / شهر / سنة","شهر / يوم / سنة"},0);
        new AlertDialog.Builder(this).setTitle("تحليل محادثة مصدّرة").setView(f).setNegativeButton("إلغاء",null).setPositiveButton("استخراج المعلومات",(d,w)->{java.util.LinkedHashMap<String,ArrayList<ChatText.Message>> chat=ChatText.parse(body,message.optLong("at"),dates.getSelectedItemPosition()==1);String person=people[sender.getSelectedItemPosition()];ArrayList<ChatText.Message> lines=chat.get(person);if(lines==null)return;StringBuilder combined=new StringBuilder();for(ChatText.Message line:lines)combined.append(line.body).append("\n");Analysis result=Analysis.inspect(combined.toString(),message.optLong("at"));result.followUp="";result.followTime="";for(ChatText.Message line:lines){Analysis one=Analysis.inspect(line.body,line.at);if(!one.followUp.isEmpty()&&(line.dated||line.body.matches("(?s).*20[0-9]{2}-[0-9]{2}-[0-9]{2}.*")))result.followUp=one.followUp;if(!one.followTime.isEmpty())result.followTime=one.followTime;}String number=Analysis.phone(person);if(!number.isEmpty())result.phone=number;chooseQuick(message,result,person);}).show();
    }
    private void chooseQuick(JSONObject message,Analysis result,String sender){
        ArrayList<JSONObject> leads=store.query("SELECT * FROM leads ORDER BY name COLLATE NOCASE LIMIT 1000");JSONObject match=result.phone.isEmpty()?new JSONObject():store.byPhone(result.phone);int selected=0;if(match.optLong("id")>0){boolean found=false;for(JSONObject lead:leads)if(lead.optLong("id")==match.optLong("id"))found=true;if(!found)leads.add(0,match);}
        String[] labels=new String[leads.size()+1];labels[0]="إنشاء عميل من المعلومات المستخرجة";for(int i=0;i<leads.size();i++){labels[i+1]=leads.get(i).optString("name")+" • "+leads.get(i).optString("phone","");if(leads.get(i).optLong("id")==match.optLong("id")&&match.optLong("id")>0)selected=i+1;}
        LinearLayout f=form();if(selected>0)muted(f,"وجدنا عميلًا بنفس الرقم؛ تم اقتراحه لتجنب التكرار.");if(result.phones.size()>1)muted(f,"ورد أكثر من رقم في النص. راجع رقم العميل؛ لن نختار أحدها من محتوى الرسالة تلقائيًا.");Spinner choose=spinner(f,"العميل",labels,selected);
        new AlertDialog.Builder(this).setTitle("ربط المعلومات بالعميل").setView(f).setNegativeButton("إلغاء",null).setPositiveButton("مراجعة وحفظ سريع",(d,w)->quickPanel(message,choose.getSelectedItemPosition()==0?new JSONObject():leads.get(choose.getSelectedItemPosition()-1),result,sender)).show();
    }
    private void quickPanel(JSONObject message,JSONObject original,Analysis result,String sender){
        JSONObject seed;try{seed=new JSONObject(original.toString());}catch(Exception e){alert("تعذر قراءة العميل");return;}LinearLayout f=form();f.addView(text("المعلومات المستخرجة",22));muted(f,"مراجعة واحدة بدل تعبئة نموذج العميل. المعلومات الموجودة لا تُستبدل إلا إذا اخترت ذلك.");boolean fresh=seed.optLong("id")==0;
        String candidateName=result.name;if(candidateName.isEmpty()&&!result.phone.isEmpty())candidateName=PhoneData.contact(this,result.phone);if(candidateName.isEmpty()&&!sender.isEmpty()&&Analysis.phone(sender).isEmpty())candidateName=sender;if(candidateName.isEmpty())candidateName=result.phone;
        EditText name=field(f,"اسم العميل أو رقمه",fresh?candidateName:seed.optString("name"),1);EditText phone=field(f,"الرقم السعودي",fresh?result.phone:seed.optString("phone"),android.text.InputType.TYPE_CLASS_PHONE);phone.setTextDirection(View.TEXT_DIRECTION_LTR);
        String suggested=AppMode.MODE;Spinner activity=spinner(f,"النشاط المقترح",new String[]{"غير محدد","أجهزة المساحة","البرامج والتطبيقات"},suggested.equals("survey")?1:suggested.equals("software")?2:0);activity.setEnabled(false);
        java.util.LinkedHashMap<String,String> values=new java.util.LinkedHashMap<>();values.put("company",result.company);values.put("email",result.email);values.put("interest",result.interest);values.put("followUp",result.followUp);values.put("followTime",result.followTime);
        java.util.Map<String,String> labels=new java.util.HashMap<>();labels.put("company","الشركة");labels.put("email","البريد");labels.put("interest","الاهتمام");labels.put("followUp","المتابعة");labels.put("followTime","الوقت");
        java.util.Map<String,CheckBox> options=new java.util.LinkedHashMap<>();for(java.util.Map.Entry<String,String> entry:values.entrySet()){if(entry.getValue().isEmpty())continue;CheckBox check=new CheckBox(this);String current=seed.optString(entry.getKey());check.setText(labels.get(entry.getKey())+": "+entry.getValue()+(current.isEmpty()?"":"\nالمحفوظ: "+current));check.setChecked((fresh||current.isEmpty())&&!(entry.getKey().equals("followUp")&&entry.getValue().compareTo(LocalDate.now().toString())<0));f.addView(check);options.put(entry.getKey(),check);}
        JSONObject all;try{all=new JSONObject(seed.optString("requestDetails","{}"));}catch(Exception e){all=new JSONObject();}final JSONObject requests=all;java.util.Map<String,CheckBox> requestOptions=new java.util.LinkedHashMap<>();
        if(!result.details.isEmpty()){f.addView(text("اقتراحات تفاصيل الطلب",19));for(java.util.Map.Entry<String,String> entry:result.details.entrySet()){CheckBox check=new CheckBox(this);check.setText(requestLabel(entry.getKey())+": "+entry.getValue());JSONObject prior=requests.optJSONObject(suggested);check.setChecked(prior==null||prior.optString(entry.getKey()).isEmpty());f.addView(check);requestOptions.put(entry.getKey(),check);}}
        final AlertDialog[] holder=new AlertDialog[1];primary(button(f,"اعتماد المعلومات وحفظ العميل",()->{try{String number=phone.getText().toString().trim();String customerName=name.getText().toString().trim();if(customerName.isEmpty())customerName=Analysis.phone(number);seed.put("name",customerName).put("phone",number).put("business",activity.getSelectedItemPosition()==1?"survey":activity.getSelectedItemPosition()==2?"software":"");for(java.util.Map.Entry<String,CheckBox> option:options.entrySet())if(option.getValue().isChecked())seed.put(option.getKey(),values.get(option.getKey()));
            android.database.sqlite.SQLiteDatabase db=store.getWritableDatabase();db.beginTransaction();try{long id=store.save(seed);String selectedBusiness=seed.optString("business");JSONObject detail=requests.optJSONObject(selectedBusiness);if(detail==null)detail=new JSONObject();boolean changed=false;for(java.util.Map.Entry<String,CheckBox> option:requestOptions.entrySet())if(option.getValue().isChecked()&&allowedDetail(selectedBusiness,option.getKey())){detail.put(option.getKey(),result.details.get(option.getKey()));changed=true;}if(changed){requests.put(selectedBusiness,detail);store.request(id,requests);}store.reviewed(message.optLong("id"),id);db.setTransactionSuccessful();}finally{db.endTransaction();}holder[0].dismiss();render();Reminders.schedule(this);alert("حُفظ العميل والمعلومات المختارة");
        }catch(android.database.sqlite.SQLiteConstraintException duplicate){alert("هذا الرقم موجود بالفعل. اختر العميل الموجود للربط.");}catch(Exception e){alert(e.getMessage()==null?"تعذر الحفظ":e.getMessage());}}));holder[0]=panel("اعتماد المعلومات",f);
    }
    private String requestLabel(String key){String[] keys={"device","model","service","condition","quantity","budget","program","platform","needs","plan","purchaseDate","calibrationDate","demoDate","subscriptionEnd"};String[] names={"الجهاز","الموديل","الخدمة","الحالة","الكمية","الميزانية","البرنامج","المنصة","الاحتياجات","الباقة","موعد الشراء","تجديد المعايرة","العرض التجريبي","انتهاء الاشتراك"};for(int i=0;i<keys.length;i++)if(keys[i].equals(key))return names[i];return key;}
    private boolean allowedDetail(String business,String key){if(business.isEmpty())return false;String keys=business.equals("survey")?"|device|model|service|condition|quantity|budget|purchaseDate|calibrationDate|":"|program|platform|needs|plan|budget|demoDate|subscriptionEnd|";return keys.contains("|"+key+"|");}
    private void pasteText(){LinearLayout f=form();EditText body=field(f,"الصق نص الرسالة أو المحادثة هنا","",android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);body.setMinLines(8);new AlertDialog.Builder(this).setTitle("تحليل نص واتساب").setView(f).setNegativeButton("إلغاء",null).setPositiveButton("تحليل",(d,w)->{String value=body.getText().toString();if(value.trim().isEmpty()||value.length()>100000){alert("أدخل نصًا حتى 100 ألف حرف");return;}saveSharedText(value,"");}).show();}
    private void saveSharedText(String body,String subject){String key=TextFingerprint.of("share|"+subject+"|"+body.trim());long now=System.currentTimeMillis();store.message(key,subject,body,now,"نص واتساب مشترك",true);ArrayList<JSONObject> list=store.query("SELECT * FROM messages WHERE fingerprint=?",key);tab="messages";render();if(!list.isEmpty()&&list.get(0).optString("state").equals("pending"))review(list.get(0));else alert("هذا النص سبق حفظه ومراجعته");}
    private void settings(){
        content.addView(text("إعدادات التطبيق",24));
        button(content,"الحاسبة • ضريبة 15%",()->startActivity(new Intent(this,CalculatorActivity.class)));
        primary(button(content,"بيانات منشأة النشاط الحالي",()->editProfile(business)));
        LinearLayout screen=content;content=card(screen);muted(content,"عام وخصوصية");content.addView(text("بياناتك محفوظة على الهاتف. هذا التطبيق مستقل؛ لا يحتاج موقعًا أو اشتراك API، ولا يرسل العملاء أو الرسائل إلى الإنترنت.",16));
        button(content,"إضافة اختصار للشاشة الرئيسية",()->{ShortcutManager manager=getSystemService(ShortcutManager.class);if(!manager.isRequestPinShortcutSupported()){alert("اسحب أيقونة عملائي من قائمة التطبيقات إلى الشاشة الرئيسية.");return;}manager.requestPinShortcut(new ShortcutInfo.Builder(this,"myclients").setShortLabel(AppMode.LABEL).setIcon(Icon.createWithResource(this,R.drawable.ic_launcher)).setIntent(new Intent(this,MainActivity.class).setAction(Intent.ACTION_VIEW)).build(),null);});
        button(content,"السماح بأسماء جهات الاتصال",()->requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},10));
        content=card(screen);content.addView(text("تنبيهات المتابعة",18));
        android.content.SharedPreferences reminderSettings=getSharedPreferences("settings",0);
        Switch reminders=new Switch(this);reminders.setText("تفعيل تذكيرات المتابعة");reminders.setChecked(reminderSettings.getBoolean("reminders",true));reminders.setOnCheckedChangeListener((v,on)->{reminderSettings.edit().putBoolean("reminders",on).apply();if(on)enableNotifications();else{getSystemService(android.app.NotificationManager.class).cancelAll();Reminders.schedule(this);}});content.addView(reminders);
        primary(button(content,"تفعيل إشعارات المتابعة",this::enableNotifications));
        button(content,"إرسال إشعار تجريبي",()->{if(!Reminders.allowed(this)){alert("فعّل إذن الإشعارات أولًا من زر التفعيل");return;}Reminders.test(this);alert("أُرسل الإشعار التجريبي؛ افحص شريط الإشعارات.");});
        button(content,"إعدادات إشعارات التطبيق",()->startActivity(new Intent(android.provider.Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,getPackageName())));
        muted(content,Reminders.allowed(this)?"إشعارات التطبيق مسموحة":"الإشعارات غير مسموحة حاليًا — امنح الإذن لإظهار التذكير");
        muted(content,"حدد تاريخ المتابعة ووقت التنبيه في بيانات العميل لأي نوع طلب. التذكير تقريبي وقد يتأخر مع توفير الطاقة؛ لا تُنبه الطلبات المكتملة أو المغلقة.");
        content=card(screen);content.addView(text("المكالمات وجهات الاتصال",18));
        android.content.SharedPreferences preferences=getSharedPreferences("settings",0);
        primary(button(content,"إعداد المكالمات والاستيراد بخطوة واحدة",this::callSetup));
        muted(content,"الرقم والاسم المتاح يُحفظان تلقائيًا. لا يلزم إدخال الشركة أو الاهتمام لإنشاء العميل.");
        RoleManager callRole=getSystemService(RoleManager.class);muted(content,callRole.isRoleAvailable(RoleManager.ROLE_CALL_SCREENING)&&callRole.isRoleHeld(RoleManager.ROLE_CALL_SCREENING)?"استقبال أرقام المكالمات: الدور ممنوح لعملائي":"استقبال أرقام المكالمات: لم يُمنح دور تحديد المتصل لعملائي");muted(content,checkSelfPermission(Manifest.permission.READ_CALL_LOG)==PackageManager.PERMISSION_GRANTED?"سجل المكالمات: الوصول مسموح":"سجل المكالمات: الوصول غير ممنوح");
        Switch sync=new Switch(this);sync.setText("تحديث سجل المكالمات تلقائيًا عند فتح التطبيق");sync.setChecked(preferences.getBoolean("autoSync",false));sync.setOnCheckedChangeListener((v,on)->preferences.edit().putBoolean("autoSync",on).apply());content.addView(sync);
        Switch calls=new Switch(this);calls.setText("إضافة أرقام المكالمات السعودية الجديدة");calls.setChecked(preferences.getBoolean("calls",false));calls.setOnCheckedChangeListener((v,on)->preferences.edit().putBoolean("calls",on).apply());content.addView(calls);
        button(content,"تفعيل تحديد هوية المتصل",()->{RoleManager role=getSystemService(RoleManager.class);if(role.isRoleAvailable(RoleManager.ROLE_CALL_SCREENING))startActivityForResult(role.createRequestRoleIntent(RoleManager.ROLE_CALL_SCREENING),11);else alert("هذا الدور غير متاح على الهاتف");});
        button(content,"استيراد سجل المكالمات السعودية",()->new AlertDialog.Builder(this).setMessage("سيُقرأ سجل الواردة والصادرة والفائتة، وتُحفظ الأرقام السعودية وأسماؤها المتاحة محليًا. هل تريد البدء؟").setNegativeButton("إلغاء",null).setPositiveButton("استيراد",(d,w)->{if(checkSelfPermission(Manifest.permission.READ_CALL_LOG)==PackageManager.PERMISSION_GRANTED)importHistory();else requestPermissions(new String[]{Manifest.permission.READ_CALL_LOG},12);}).show());
        content.addView(text("إذن سجل المكالمات مقيد من أندرويد وقد يرفضه المثبّت. استقبال المكالمات الجديدة لا يمنح الوصول للسجل القديم.",14));
        content=card(screen);content.addView(text("رسائل واتساب",18));
        content.addView(text("واتساب: المشاركة اليدوية فقط. لا يطلب هذا الإصدار الوصول إلى الإشعارات ولا يقرأها في الخلفية. شارك نص الرسالة أو ملف TXT إلى عملائي ثم راجع المعلومات قبل الحفظ.",16));
        content=card(screen);content.addView(text("النسخ الاحتياطي",18));
        button(content,"نسخة احتياطية محلية",()->{Intent intent=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").putExtra(Intent.EXTRA_TITLE,"myclients-backup.json").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(intent,20);});
        button(content,"استعادة نسخة احتياطية",()->new AlertDialog.Builder(this).setMessage("الاستعادة تستبدل العملاء والرسائل والمنشورات وملفات المنشآت في النسخ الجديدة. أنشئ نسخة احتياطية أولًا.").setNegativeButton("إلغاء",null).setPositiveButton("اختيار النسخة",(d,w)->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE),21)).show());
        content.addView(text("ملف النسخة الاحتياطية يحتوي بيانات العملاء والرسائل بنص مقروء؛ احتفظ به في مكان خاص بك.",14));
        content=screen;
        content.addView(text(preferences.getString("status",""),16));
        content.addView(text("التحليل محلي بالكلمات والصيغ: اقتراح اهتمام ونشاط وموعد وبريد ورقم. ليس تحليلًا سحابيًا بالذكاء الاصطناعي. البحث الخارجي عن معلومات الأرقام غير مفعل.",14));
    }
    private void importHistory(){syncHistory(true);}
    private void syncHistory(boolean showResult){if(importing)return;importing=true;getSharedPreferences("settings",0).edit().putLong("lastSync",System.currentTimeMillis()).apply();History.status(this,"جارٍ إنشاء العملاء من سجل المكالمات…");new Thread(()->{History.run(getApplicationContext());runOnUiThread(()->{importing=false;if(isFinishing()||isDestroyed())return;if(showResult)tab="unassigned";render();if(showResult)alert(getSharedPreferences("settings",0).getString("status",""));});},"history").start();}
    private void callSetup(){LinearLayout f=form();muted(f,"يُنشأ العميل تلقائيًا من الرقم والاسم المتاح. لن تُطلب منك بقية البيانات. سيُحدّث السجل عند فتح التطبيق إذا سمح الهاتف بالوصول إليه.");Spinner activity=spinner(f,"النشاط الافتراضي للأرقام الجديدة",new String[]{"اتركه غير محدد للمراجعة الجماعية","أجهزة المساحة","البرامج والتطبيقات"},getSharedPreferences("settings",0).getString("newBusiness","").equals("survey")?1:getSharedPreferences("settings",0).getString("newBusiness","").equals("software")?2:0);activity.setSelection(AppMode.MODE.equals("survey")?1:2);activity.setEnabled(false);new AlertDialog.Builder(this).setTitle("إعداد المكالمات").setView(f).setNegativeButton("إلغاء",null).setPositiveButton("تفعيل واستيراد",(d,w)->{getSharedPreferences("settings",0).edit().putBoolean("calls",true).putBoolean("autoSync",true).putString("newBusiness",activity.getSelectedItemPosition()==1?"survey":activity.getSelectedItemPosition()==2?"software":"").apply();RoleManager role=getSystemService(RoleManager.class);if(role.isRoleAvailable(RoleManager.ROLE_CALL_SCREENING)&&!role.isRoleHeld(RoleManager.ROLE_CALL_SCREENING)){getSharedPreferences("settings",0).edit().putBoolean("setupPending",true).apply();startActivityForResult(role.createRequestRoleIntent(RoleManager.ROLE_CALL_SCREENING),11);}else requestCallPermissions();}).show();}
    private void requestCallPermissions(){if(checkSelfPermission(Manifest.permission.READ_CALL_LOG)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.READ_CONTACTS)==PackageManager.PERMISSION_GRANTED)importHistory();else requestPermissions(new String[]{Manifest.permission.READ_CALL_LOG,Manifest.permission.READ_CONTACTS},12);}
    private void assignCalls(){if(selectedCalls.isEmpty()){alert("حدد العملاء أولًا");return;}int n=store.assign(new java.util.ArrayList<>(selectedCalls),AppMode.MODE);selectedCalls.clear();render();alert("تم تعيين "+n+" عميل لهذا التطبيق");}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(request==13){Reminders.channel(this);Reminders.deliver(this);Reminders.schedule(this);render();if(grants.length==0||grants[0]!=PackageManager.PERMISSION_GRANTED)alert("لم يُمنح إذن الإشعارات. تبقى المتابعات ظاهرة في قائمة اليوم.");}if(request==12){if(checkSelfPermission(Manifest.permission.READ_CALL_LOG)==PackageManager.PERMISSION_GRANTED)importHistory();else alert("لم يُمنح إذن السجل. يمكنك إضافة العملاء يدويًا واستقبال المكالمات الجديدة عند تفعيل دور تحديد المتصل.");}}
    private String read(Uri uri,int max) throws Exception {if(!"content".equals(uri.getScheme()))throw new IllegalArgumentException("اختر ملفًا من مدير المستندات");try(java.io.InputStream input=getContentResolver().openInputStream(uri);java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream()){if(input==null)throw new java.io.IOException();byte[] buffer=new byte[4096];int n;while((n=input.read(buffer))!=-1){bytes.write(buffer,0,n);if(bytes.size()>max)throw new IllegalArgumentException("الملف كبير جدًا؛ شارك نصًا أصغر");}return bytes.toString("UTF-8");}}
    private void receive(Intent intent){long open=intent.getLongExtra("openLead",0);if(open>0){JSONObject item=store.lead(open);if(item.optLong("id")>0){business=AppMode.MODE;requestFilter=0;tab="today";render();edit(item,0);}intent.removeExtra("openLead");}if(!Intent.ACTION_SEND.equals(intent.getAction()))return;try{
        String body=intent.getStringExtra(Intent.EXTRA_TEXT);Uri stream=intent.getParcelableExtra(Intent.EXTRA_STREAM);if(stream!=null)body=read(stream,1024*1024);
        if(body==null||body.trim().isEmpty()){alert("شارك نص رسالة أو ملف محادثة نصيًا دون الوسائط");return;}
        if(body.length()>100000){alert("المحادثة طويلة جدًا؛ شارك جزءًا أصغر (حتى 100 ألف حرف)");return;}
        String sender=intent.getStringExtra(Intent.EXTRA_SUBJECT);long now=System.currentTimeMillis();intent.setAction(Intent.ACTION_VIEW);saveSharedText(body,sender==null?"":sender);
    }catch(Exception e){alert("تعذر قراءة المشاركة؛ جرّب مشاركة نص الرسالة فقط");}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==30){if(postDraft==null)return;if(result==RESULT_OK&&data!=null&&data.getData()!=null)try{postDraft.put("image",PostMedia.importUri(this,data.getData()));}catch(Exception e){alert(e.getMessage()==null?"تعذر إضافة الصورة":e.getMessage());}editPost(postDraft);return;}if(request==11&&getSharedPreferences("settings",0).getBoolean("setupPending",false)){getSharedPreferences("settings",0).edit().putBoolean("setupPending",false).apply();requestCallPermissions();return;}if(result!=RESULT_OK||data==null||data.getData()==null)return;try{
        if(request==20){try(java.io.OutputStream output=getContentResolver().openOutputStream(data.getData())){if(output==null)throw new java.io.IOException();output.write(store.backup().toString(2).getBytes("UTF-8"));}alert("حُفظت النسخة الاحتياطية");}
        if(request==21){store.restore(new JSONObject(read(data.getData(),25*1024*1024)));getSystemService(android.app.NotificationManager.class).cancelAll();getSharedPreferences("settings",0).edit().putLong("historyId",0).apply();render();Reminders.schedule(this);alert("اكتملت الاستعادة");}
    }catch(Exception e){alert("تعذر حفظ أو استعادة النسخة: "+(e.getMessage()==null?"تحقق من الملف والمساحة":e.getMessage())+". عند فشل الاستعادة لا تُستبدل قاعدة البيانات جزئيًا.");}}

    private void followAction(long id,boolean tomorrow){new AlertDialog.Builder(this).setMessage(tomorrow?"تأجيل موعد المتابعة المحفوظ إلى الغد بنفس الوقت؟":"تسجيل إتمام المتابعة وإزالة الموعد الحالي؟").setNegativeButton("إلغاء",null).setPositiveButton("تأكيد",(d,w)->{try{store.finishFollowUp(id,tomorrow);getSystemService(android.app.NotificationManager.class).cancel("lead",(int)id);Reminders.schedule(this);render();alert(tomorrow?"تم تأجيل المتابعة. أعد فتح العميل لرؤية الموعد الجديد.":"تم إتمام المتابعة. أعد فتح العميل لرؤية التحديث.");}catch(Exception e){alert("تعذر تحديث الموعد");}}).show();}
    private AlertDialog panel(String title,LinearLayout form){ScrollView scroll=new ScrollView(this);scroll.addView(form);AlertDialog d=new AlertDialog.Builder(this).setTitle(title).setView(scroll).setNegativeButton("إغلاق",null).create();d.show();d.getWindow().setBackgroundDrawable(shape(Color.WHITE,20,0));d.getWindow().setLayout(-1,-1);return d;}
    private LinearLayout form(){LinearLayout f=column();f.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);f.setPadding(dp(20),dp(12),dp(20),dp(20));return f;}
    private void timeline(long id){
        JSONObject lead=store.lead(id);LinearLayout f=form();f.addView(text(lead.optString("name"),22));muted(f,"المكالمات المسجلة والملاحظات والتغييرات — أحدث 200 تعامل");
        EditText note=field(f,"أضف ملاحظة للتعامل", "",android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);
        final AlertDialog[] holder=new AlertDialog[1];primary(button(f,"حفظ الملاحظة",()->{String value=note.getText().toString().trim();if(value.isEmpty()){alert("اكتب الملاحظة أولًا");return;}store.event(id,"note",value,System.currentTimeMillis(),null);holder[0].dismiss();timeline(id);}));
        ArrayList<JSONObject> items=store.query("SELECT * FROM events WHERE leadId=? ORDER BY at DESC,id DESC LIMIT 200",String.valueOf(id));
        if(items.isEmpty())muted(f,"لا يوجد سجل تعاملات بعد. التحديث لا يستنتج أحداثًا قديمة لم تُسجّل.");
        for(JSONObject item:items){LinearLayout box=card(f);muted(box,android.text.format.DateFormat.format("yyyy-MM-dd HH:mm",item.optLong("at")).toString());TextView body=text(item.optString("body"),15);body.setTextIsSelectable(true);box.addView(body);}
        holder[0]=panel("سجل التعاملات",f);
    }
    private void requestDetails(long id){
        JSONObject lead=store.lead(id);String activity=lead.optString("business");if(activity.isEmpty()){alert("حدد نشاط العميل واحفظه أولًا");return;}
        JSONObject all;try{all=new JSONObject(lead.optString("requestDetails","{}"));}catch(Exception e){all=new JSONObject();}final JSONObject details=all;JSONObject values=all.optJSONObject(activity);if(values==null)values=new JSONObject();
        String[][] fields=activity.equals("survey")?SurveyRequests.fields(lead.optString("requestType","sales")):new String[][]{{"program","البرنامج المطلوب"},{"platform","سحابي / مكتبي / تطبيق"},{"needs","احتياجات العميل"},{"demoDate","موعد العرض التجريبي (YYYY-MM-DD)"},{"plan","الباقة المطلوبة"},{"budget","الميزانية المتوقعة (ريال)"},{"subscriptionEnd","انتهاء الاشتراك (YYYY-MM-DD)"}};
        LinearLayout f=form();f.addView(text(activity.equals("survey")?"طلب أجهزة المساحة":"طلب البرامج والتطبيقات",22));muted(f,"تفاصيل خاصة بالنشاط المحفوظ لهذا العميل");if(activity.equals("survey"))muted(f,"نوع الطلب الحالي: "+SurveyRequests.label(lead.optString("requestType","sales"))+" • عدله من بيانات العميل");java.util.Map<String,EditText> inputs=new java.util.LinkedHashMap<>();
        for(String[] item:fields){int type=item[0].equals("quantity")?android.text.InputType.TYPE_CLASS_NUMBER:item[0].equals("budget")?android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL:item[0].equals("issue")||item[0].equals("workDone")?android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE:android.text.InputType.TYPE_CLASS_TEXT;inputs.put(item[0],field(f,item[1],values.optString(item[0]),type));}
        final JSONObject savedValues=values;final AlertDialog[] holder=new AlertDialog[1];primary(button(f,"حفظ تفاصيل الطلب",()->{try{JSONObject data=new JSONObject(savedValues.toString());for(String[] item:fields){String value=inputs.get(item[0]).getText().toString().trim();if(!value.isEmpty()&&(item[0].endsWith("Date")||item[0].equals("subscriptionEnd")))LocalDate.parse(value);if(!value.isEmpty()&&item[0].equals("quantity")&&Integer.parseInt(value)<1)throw new IllegalArgumentException("الكمية يجب أن تكون أكبر من صفر");if(!value.isEmpty()&&item[0].equals("budget")&&new java.math.BigDecimal(value).signum()<0)throw new IllegalArgumentException("الميزانية غير صالحة");data.put(item[0],value);}details.put(activity,data);store.request(id,details);holder[0].dismiss();alert("حُفظت تفاصيل الطلب");}catch(Exception e){alert("تحقق من الكمية والميزانية والتواريخ بصيغة YYYY-MM-DD");}}));holder[0]=panel("تفاصيل الطلب",f);
    }
    private void templates(long id){JSONObject lead=store.lead(id);String interest=lead.optString("interest");if(interest.isEmpty())interest=lead.optString("business").equals("software")?"البرنامج المطلوب":"الجهاز أو الخدمة المطلوبة";
        String intro="السلام عليكم "+lead.optString("name")+"،\n";
        String[] titles=lead.optString("business").equals("survey")&&!lead.optString("requestType","sales").equals("sales")?new String[]{"متابعة طلب الخدمة","متابعة تفاصيل الطلب","تأكيد موعد","متابعة بعد إتمام الخدمة"}:new String[]{"متابعة الاهتمام","متابعة عرض السعر","تأكيد موعد","متابعة بعد البيع"};
        String[] bodies={intro+"يسعدنا متابعة طلبك بخصوص "+interest+". هل توجد تفاصيل إضافية أو استفسارات يمكننا مساعدتك بها؟",intro+"نود متابعة عرض السعر الخاص بـ "+interest+". هل اطلعت عليه، وهل ترغب في توضيح أي بند؟",intro+"نود تأكيد موعد المتابعة "+(lead.optString("followUp").isEmpty()?"[اكتب التاريخ والوقت]":lead.optString("followUp")+" "+lead.optString("followTime","09:00"))+" بخصوص "+interest+". هل الموعد مناسب لك؟",intro+"نتمنى أن تكون تجربتك مع "+interest+" جيدة. هل تحتاج أي مساعدة أو متابعة إضافية؟"};
        if(lead.optString("business").equals("survey")&&!lead.optString("requestType","sales").equals("sales"))bodies[1]=intro+"نتابع طلب "+SurveyRequests.label(lead.optString("requestType"))+" بخصوص "+interest+". هل توجد تفاصيل إضافية عن الجهاز أو المشكلة؟";
        new AlertDialog.Builder(this).setTitle("اختر قالب رسالة").setItems(titles,(d,which)->{LinearLayout f=form();EditText body=field(f,"راجع النص وعدّله قبل الإرسال",bodies[which],android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);body.setMinLines(7);muted(f,"فتح واتساب يجهز النص فقط. تضغط إرسال داخل واتساب بنفسك.");new AlertDialog.Builder(this).setTitle(titles[which]).setView(f).setNegativeButton("إلغاء",null).setNeutralButton("نسخ النص",(dialog,w)->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("رسالة العميل",body.getText().toString()));}).setPositiveButton("فتح واتساب",(dialog,w)->{String phone=lead.optString("phone");if(phone.isEmpty()||phone.equals("null")){alert("أضف رقم العميل أو استخدم نسخ النص");return;}try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://wa.me/"+phone.replace("+","")+"?text="+Uri.encode(body.getText().toString()))));store.event(id,"template","تجهيز قالب واتساب: "+titles[which]+" — لا يؤكد إرسال الرسالة",System.currentTimeMillis(),null);}catch(Exception e){alert("تعذر فتح واتساب؛ استخدم نسخ النص");}}).show();}).show();
    }

    private static final String[] POST_CATEGORIES={"تعريف","عرض","معلومة","نصيحة","مقارنة","تجربة استخدام"};
    private void advertising(){
        content.addView(text(business.equals("survey")?"دعاية أجهزة المساحة":"دعاية البرامج والتطبيقات",24));
        JSONObject company=store.profile(business);muted(content,company.optString("name").isEmpty()?"أضف بيانات منشأة هذا النشاط":company.optString("name"));button(content,"بيانات المنشأة وصفحات التسويق",()->editProfile(business));muted(content,"مكتبة مستقلة لهذا النشاط • صور ونصوص جاهزة للمشاركة");
        JSONObject total=store.query("SELECT COUNT(*) AS total,SUM(CASE WHEN lastPreparedAt=0 THEN 1 ELSE 0 END) AS unused,SUM(CASE WHEN plannedDate<>'' AND plannedDate<=? THEN 1 ELSE 0 END) AS due FROM posts WHERE business=?",LocalDate.now().toString(),business).get(0);LinearLayout stats=row();content.addView(stats);metric(stats,"منشورات",total.optInt("total"),BLUE);metric(stats,"لم تُفتح",total.optInt("unused"),0xFF348C76);metric(stats,"مخطط لها",total.optInt("due"),0xFFD69538);
        primary(button(content,"+  إضافة صورة أو منشور",()->{try{editPost(new JSONObject().put("business",business));}catch(Exception e){alert("تعذر فتح المحرر");}}));button(content,"تجهيز ثلاث صيغ للنص",this::adCopy);
        Spinner filter=spinner(content,"عرض المكتبة",new String[]{"كل المنشورات","المخطط لليوم والمتأخر","لم يُفتح للمشاركة بعد"},adFilter);filter.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int i,long id){if(adFilter!=i){adFilter=i;adLimit=20;render();}}});
        muted(content,"تاريخ المشاركة يعني فتح نافذة المشاركة؛ لا يثبت إرسال المنشور. يوم النشر تخطيط فقط، ولا يُرسل التطبيق تلقائيًا.");
        String condition=adFilter==1?" AND plannedDate<>'' AND plannedDate<=?":adFilter==2?" AND lastPreparedAt=0":"";ArrayList<JSONObject> posts=adFilter==1?store.query("SELECT * FROM posts WHERE business=?"+condition+" ORDER BY plannedDate,createdAt DESC LIMIT 21 OFFSET "+(adLimit-20),business,LocalDate.now().toString()):store.query("SELECT * FROM posts WHERE business=?"+condition+" ORDER BY createdAt DESC LIMIT 21 OFFSET "+(adLimit-20),business);
        if(posts.isEmpty())empty("جهّز أول منشور لهذا النشاط","أضف صورة من هاتفك ونصًا قصيرًا؛ ستجده هنا عند الحاجة");int count=0;for(JSONObject post:posts){if(count++>=20)break;LinearLayout box=card(content);box.addView(text(post.optString("title"),20));box.addView(pill(post.optString("category"),BLUE,0xFFF1EEFC));showPostImage(box,post.optString("image"));String body=post.optString("body");if(!body.isEmpty()){TextView caption=text(body.length()>650?body.substring(0,650)+"…":body,14);caption.setTextIsSelectable(true);box.addView(caption);}if(!post.optString("plannedDate").isEmpty())muted(box,"يوم النشر المخطط: "+post.optString("plannedDate"));muted(box,post.optLong("lastPreparedAt")==0?"لم تُفتح المشاركة بعد":"آخر فتح للمشاركة: "+android.text.format.DateFormat.format("yyyy-MM-dd HH:mm",post.optLong("lastPreparedAt")));
            primary(button(box,"مشاركة الصورة والنص",()->sharePost(post)));LinearLayout actions=row();box.addView(actions);Button edit=button(actions,"تعديل",()->editPost(post));edit.setLayoutParams(new LinearLayout.LayoutParams(0,dp(44),1));Button copy=button(actions,"نسخة جديدة",()->{try{JSONObject duplicate=new JSONObject(post.toString());duplicate.remove("id");duplicate.put("title",post.optString("title")+" — نسخة").put("plannedDate","");store.savePost(duplicate);render();}catch(Exception e){alert("تعذر إنشاء نسخة");}});LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(44),1);cp.setMargins(dp(6),0,dp(6),0);copy.setLayoutParams(cp);button(box,"سجل فتح المشاركة",()->{StringBuilder log=new StringBuilder();for(JSONObject item:store.query("SELECT at FROM postShares WHERE postId=? ORDER BY at DESC LIMIT 50",String.valueOf(post.optLong("id"))))log.append(android.text.format.DateFormat.format("yyyy-MM-dd HH:mm",item.optLong("at"))).append("\n");alert(log.length()==0?"لم يُفتح للمشاركة بعد":log.toString());});
        }if(adLimit>20)button(content,"الصفحة السابقة",()->{adLimit-=20;render();});if(posts.size()>20)button(content,"الصفحة التالية",()->{adLimit+=20;render();});
    }
    private void showPostImage(LinearLayout parent,String name){if(name.isEmpty())return;android.graphics.Bitmap bitmap=PostMedia.thumbnail(this,name);if(bitmap==null){muted(parent,"الصورة غير متاحة؛ أعد إضافتها");return;}ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setContentDescription("صورة المنشور");LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(210));lp.setMargins(0,dp(12),0,dp(8));parent.addView(image,lp);}
    private void capturePost(){if(postDraft==null)return;try{for(java.util.Map.Entry<String,EditText> entry:postInputs.entrySet())postDraft.put(entry.getKey(),entry.getValue().getText().toString());if(postCategory!=null)postDraft.put("category",POST_CATEGORIES[postCategory.getSelectedItemPosition()]);}catch(Exception ignored){}}
    private void editPost(JSONObject original){
        if(postDialog!=null&&postDialog.isShowing())postDialog.dismiss();try{postDraft=new JSONObject(original.toString());if(!postDraft.has("business"))postDraft.put("business",business);}catch(Exception e){alert("تعذر فتح المنشور");return;}postInputs.clear();LinearLayout f=form();f.addView(text(postDraft.optString("business").equals("survey")?"منشور أجهزة المساحة":"منشور البرامج والتطبيقات",22));muted(f,"يُحفظ في مكتبة هذا النشاط فقط");
        button(f,"إدراج بيانات منشأة هذا النشاط في النص",()->{EditText text=postInputs.get("body");if(text==null)return;String footer=profileFooter(postDraft.optString("business"),true);if(footer.isEmpty()){alert("أضف بيانات المنشأة من الإعدادات أولًا");return;}if(!text.getText().toString().contains(footer))text.append("\n\n"+footer);});
        postInputs.put("title",field(f,"عنوان داخلي للمنشور",postDraft.optString("title"),1));EditText body=field(f,"النص المصاحب للصورة",postDraft.optString("body"),android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);body.setMinLines(5);postInputs.put("body",body);
        int category=0;for(int i=0;i<POST_CATEGORIES.length;i++)if(POST_CATEGORIES[i].equals(postDraft.optString("category")))category=i;postCategory=spinner(f,"نوع المحتوى",POST_CATEGORIES,category);showPostImage(f,postDraft.optString("image"));button(f,"اختيار صورة من الهاتف",()->{capturePost();postDialog.dismiss();startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),30);});if(!postDraft.optString("image").isEmpty())button(f,"إزالة الصورة من المنشور",()->{capturePost();try{postDraft.put("image","");editPost(postDraft);}catch(Exception ignored){}});muted(f,"صور JPG / PNG / WEBP / GIF حتى 3 ميغابايت. تُحفظ الصورة الأصلية دون تعديل.");
        button(f,"تجهيز صورة بقالب جاهز",()->{capturePost();designPost();});
        EditText date=field(f,"يوم النشر المخطط (اختياري)",postDraft.optString("plannedDate"),1);postInputs.put("plannedDate",date);button(f,"اختيار يوم النشر",()->{LocalDate today=LocalDate.now();new DatePickerDialog(this,(v,y,m,d)->date.setText(LocalDate.of(y,m+1,d).toString()),today.getYear(),today.getMonthValue()-1,today.getDayOfMonth()).show();});button(f,"إزالة يوم النشر",()->date.setText(""));muted(f,"هذا تنظيم للمحتوى فقط؛ لا توجد جدولة إرسال تلقائي إلى الجروبات.");
        primary(button(f,"حفظ المنشور",()->{capturePost();try{store.savePost(postDraft);postDialog.dismiss();postDraft=null;postInputs.clear();tab="ads";render();}catch(Exception e){alert(e.getMessage()==null?"تعذر حفظ المنشور":e.getMessage());}}));if(postDraft.optLong("id")>0){long id=postDraft.optLong("id");button(f,"حذف المنشور",()->new AlertDialog.Builder(this).setMessage("حذف هذا المنشور وسجل فتح مشاركته؟").setNegativeButton("إلغاء",null).setPositiveButton("حذف",(d,w)->{store.removePost(id);postDialog.dismiss();postDraft=null;postInputs.clear();render();}).show());}
        ScrollView scroll=new ScrollView(this);scroll.addView(f);postDialog=new AlertDialog.Builder(this).setTitle("محرر الدعاية").setView(scroll).setNegativeButton("إلغاء",(d,w)->{postDraft=null;postInputs.clear();}).create();postDialog.setCancelable(false);postDialog.show();postDialog.getWindow().setBackgroundDrawable(shape(Color.WHITE,20,0));postDialog.getWindow().setLayout(-1,-1);
    }
    private void sharePost(JSONObject post){try{String body=post.optString("body"),image=post.optString("image");Intent send=new Intent(Intent.ACTION_SEND).putExtra(Intent.EXTRA_TEXT,body).putExtra(Intent.EXTRA_TITLE,post.optString("title"));if(image.isEmpty())send.setType("text/plain");else{if(!PostMedia.file(this,image).isFile())throw new java.io.IOException("الصورة غير موجودة");Uri uri=new Uri.Builder().scheme("content").authority("com.amalaei.engineering.images").appendPath(image).build();send.setType(PostMedia.mime(image)).putExtra(Intent.EXTRA_STREAM,uri).setClipData(android.content.ClipData.newUri(getContentResolver(),"صورة المنشور",uri));send.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);}startActivity(Intent.createChooser(send,"اختر واتساب ثم الجروب"));store.preparedPost(post.optLong("id"));}catch(Exception e){alert("تعذر فتح المشاركة: "+(e.getMessage()==null?"تحقق من توفر تطبيق للمشاركة":e.getMessage()));}}
    private void adCopy(){
        final String activity=business;LinearLayout f=form();muted(f,"قوالب نصية محلية مجانية؛ لا تولّد صورًا ولا تضيف خصمًا أو وعدًا من تلقاء نفسها.");EditText product=field(f,activity.equals("survey")?"الجهاز أو الخدمة":"البرنامج أو الميزة","",1),benefit=field(f,"الفائدة أو المعلومات التي تريد إبرازها","",android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE),brand=field(f,"اسم النشاط (اختياري)",profileBrand(activity),1),contact=field(f,"بيانات المنشأة المصاحبة للنص — يمكنك تعديلها لهذا المنشور",profileFooter(activity,false),android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);
        new AlertDialog.Builder(this).setTitle("ثلاث أفكار للنص").setView(f).setNegativeButton("إلغاء",null).setPositiveButton("تجهيز الصيغ",(d,w)->{String item=product.getText().toString().trim(),info=benefit.getText().toString().trim();if(item.isEmpty()||info.isEmpty()){alert("أدخل المنتج أو الميزة والفائدة أولًا");return;}String company=brand.getText().toString().trim(),phone=contact.getText().toString().trim();String footer=(company.isEmpty()?"":"\n\n"+company)+"\nراسلنا لمعرفة التفاصيل"+(phone.isEmpty()?"":"\n"+phone);String[] titles={"تعريف مباشر","سؤال يجذب الاهتمام","منشور معلوماتي"};String[] copies={item+"\n\n"+info+footer,"هل تبحث عن "+item+"؟\n\n"+info+footer,"قبل اختيار "+item+"، تعرّف على ما يفيد احتياجك:\n\n"+info+footer};LinearLayout choices=form();final AlertDialog[] holder=new AlertDialog[1];for(int i=0;i<3;i++){final int index=i;LinearLayout box=card(choices);box.addView(text(titles[i],19));TextView preview=text(copies[i],15);preview.setTextIsSelectable(true);box.addView(preview);button(box,"استخدام هذه الصيغة",()->{try{holder[0].dismiss();editPost(new JSONObject().put("business",activity).put("title",item+" — "+titles[index]).put("body",copies[index]).put("category",index==2?"معلومة":"تعريف"));}catch(Exception e){alert("تعذر تجهيز المنشور");}});button(box,"نسخ النص",()->((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("نص الدعاية",copies[index])));}holder[0]=panel("اختر الصيغة وعدّلها",choices);}).show();
    }

    private void designPost(){if(postDraft==null)return;LinearLayout f=form();muted(f,"قالب محلي 1080×1350. الصورة الحالية تُوضع داخل القالب دون إزالة الخلفية. راجع المعاينة ثم احفظ المنشور.");EditText title=field(f,"عنوان الصورة",postDraft.optString("title"),1),summary=field(f,"نص قصير على الصورة (حتى 180 حرفًا)","",android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE);String activity=postDraft.optString("business");EditText brand=field(f,"اسم النشاط",profileBrand(activity),1),contact=field(f,"التواصل أو الدعوة للإجراء",profileContact(activity),1);Spinner theme=spinner(f,"ألوان التصميم",new String[]{"بنفسجي فاتح","أخضر فاتح","برتقالي فاتح"},activity.equals("survey")?2:0);
        new AlertDialog.Builder(this).setTitle("تصميم صورة للمنشور").setView(f).setNegativeButton("إلغاء",null).setPositiveButton("إنشاء المعاينة",(d,w)->{String headline=title.getText().toString().trim(),detail=summary.getText().toString().trim(),identity=brand.getText().toString().trim(),call=contact.getText().toString().trim();if(headline.isEmpty()||headline.length()>80||detail.length()>180||identity.length()>60||call.length()>60){alert("اختصر العنوان إلى 80 حرفًا والنص إلى 180 واسم النشاط والتواصل إلى 60 حرفًا");return;}try{String image=PostDesigns.create(this,postDraft.optString("image"),headline,detail,identity,call,theme.getSelectedItemPosition());postDraft.put("image",image);editPost(postDraft);}catch(Exception e){alert(e.getMessage()==null?"تعذر إنشاء التصميم":e.getMessage());}}).show();
    }

    private String profileBrand(String activity){JSONObject data=store.profile(activity);return data.optString("brand").isEmpty()?data.optString("name"):data.optString("brand");}
    private String profileContact(String activity){JSONObject data=store.profile(activity);String phone=Profiles.firstPhone(data.optString("phones"));return phone.isEmpty()?data.optString("whatsapp"):phone;}
    private String profileFooter(String activity,boolean includeName){JSONObject data=store.profile(activity);StringBuilder footer=new StringBuilder();if(includeName&&!profileBrand(activity).isEmpty())footer.append(profileBrand(activity));JSONObject choices=data.optJSONObject("advertising");for(String key:Profiles.AD_FIELDS){boolean usual=key.equals("address")||key.equals("phones")||key.equals("whatsapp")||key.equals("website");if(choices!=null?!choices.optBoolean(key,usual):!usual)continue;String value=data.optString(key).trim();if(value.isEmpty())continue;if(footer.length()>0)footer.append("\n");footer.append(Profiles.label(key)).append(": ").append(value);}return footer.toString();}
    private void editProfile(String activity){
        final JSONObject data=store.profile(activity);LinearLayout f=form();f.addView(text(activity.equals("survey")?"منشأة أجهزة المساحة":"منشأة البرامج والتطبيقات",23));muted(f,"هذا الملف مستقل تمامًا. لا ننسخ البيانات أو أرقام التواصل بين النشاطين.");java.util.Map<String,EditText> inputs=new java.util.LinkedHashMap<>();for(String[] pair:Profiles.FIELDS){int type=pair[0].equals("address")||pair[0].equals("nationalAddress")||pair[0].equals("phones")?android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE:pair[0].equals("email")?android.text.InputType.TYPE_CLASS_TEXT|android.text.InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS:1;EditText field=field(f,pair[1],data.optString(pair[0]),type);inputs.put(pair[0],field);for(String link:Profiles.LINKS)if(link.equals(pair[0])){field.setTextDirection(View.TEXT_DIRECTION_LTR);field.setHint("https://...");}}
        f.addView(text("ما يُدرج في نصوص الدعاية",20));muted(f,"اختر البيانات التي تريد إضافتها تلقائيًا. السجل التجاري والرقم الضريبي يُحفظان في الملف ولا يُدرجان في الدعاية.");JSONObject existing=data.optJSONObject("advertising");java.util.Map<String,CheckBox> flags=new java.util.LinkedHashMap<>();for(String key:Profiles.AD_FIELDS){boolean usual=key.equals("address")||key.equals("phones")||key.equals("whatsapp")||key.equals("website");CheckBox check=new CheckBox(this);check.setText(Profiles.label(key));check.setChecked(existing==null?usual:existing.optBoolean(key,usual));f.addView(check);flags.put(key,check);}
        final AlertDialog[] holder=new AlertDialog[1];primary(button(f,"حفظ بيانات هذه المنشأة",()->{try{for(java.util.Map.Entry<String,EditText> entry:inputs.entrySet())data.put(entry.getKey(),entry.getValue().getText().toString().trim());JSONObject choices=new JSONObject();for(java.util.Map.Entry<String,CheckBox> entry:flags.entrySet())choices.put(entry.getKey(),entry.getValue().isChecked());data.put("advertising",choices);store.saveProfile(activity,data);holder[0].dismiss();render();alert("حُفظت بيانات المنشأة لهذا النشاط فقط");}catch(Exception e){alert(e.getMessage()==null?"تحقق من البيانات والروابط":e.getMessage());}}));
        button(f,"نسخ بيانات المنشأة المحفوظة",()->{StringBuilder text=new StringBuilder();JSONObject saved=store.profile(activity);for(String[] pair:Profiles.FIELDS){String value=saved.optString(pair[0]);if(!value.isEmpty())text.append(pair[1]).append(": ").append(value).append("\n");}((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("بيانات المنشأة",text.toString()));});for(String key:Profiles.LINKS){String value=data.optString(key);if(!value.isEmpty())button(f,"فتح "+Profiles.label(key),()->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(Profiles.url(value))));}catch(Exception e){alert("تعذر فتح الرابط");}});}holder[0]=panel("بيانات المنشأة",f);
    }
}
