package com.amalaei.engineering;
import android.content.Context;
import android.net.Uri;
import android.graphics.*;
import org.json.*;
import java.io.*;
import java.util.*;
final class PostMedia {
    static final int MAX_IMAGE=3*1024*1024,MAX_BACKUP_IMAGES=12*1024*1024;
    static final class RestorePlan {final LinkedHashMap<String,byte[]> images=new LinkedHashMap<>();}
    static File file(Context c,String name) throws IOException {if(!name.matches("[a-f0-9]{64}\\.(jpg|png|webp|gif)"))throw new IOException("اسم صورة غير صالح");File dir=new File(c.getFilesDir(),"post-images");if(!dir.exists()&&!dir.mkdirs())throw new IOException("تعذر إنشاء مجلد الصور");return new File(dir,name);}
    static String hash(byte[] bytes) throws Exception {byte[] digest=java.security.MessageDigest.getInstance("SHA-256").digest(bytes);StringBuilder b=new StringBuilder();for(byte value:digest)b.append(String.format(java.util.Locale.US,"%02x",value&255));return b.toString();}
    static String extension(byte[] data) throws Exception {BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(data,0,data.length,o);if(o.outWidth<=0||o.outHeight<=0||(long)o.outWidth*o.outHeight>50000000)throw new IOException("اختر صورة صالحة وبأبعاد أصغر");if("image/jpeg".equals(o.outMimeType))return "jpg";if("image/png".equals(o.outMimeType))return "png";if("image/webp".equals(o.outMimeType))return "webp";if("image/gif".equals(o.outMimeType))return "gif";throw new IOException("الصيغ المدعومة: JPG وPNG وWEBP وGIF");}
    static String save(Context c,byte[] data) throws Exception {if(data.length>MAX_IMAGE)throw new IOException("اختر صورة لا تتجاوز 3 ميغابايت");String name=hash(data)+"."+extension(data);File dest=file(c,name);if(!dest.exists()){android.util.AtomicFile atomic=new android.util.AtomicFile(dest);FileOutputStream out=null;try{out=atomic.startWrite();out.write(data);atomic.finishWrite(out);}catch(Exception e){if(out!=null)atomic.failWrite(out);throw e;}}return name;}
    static String importUri(Context c,Uri uri) throws Exception {if(!"content".equals(uri.getScheme()))throw new IOException("اختر الصورة من منتقي الملفات");try(InputStream in=c.getContentResolver().openInputStream(uri);ByteArrayOutputStream bytes=new ByteArrayOutputStream()){if(in==null)throw new IOException("تعذر قراءة الصورة");byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){bytes.write(buffer,0,n);if(bytes.size()>MAX_IMAGE)throw new IOException("اختر صورة لا تتجاوز 3 ميغابايت");}return save(c,bytes.toByteArray());}}
    static Bitmap thumbnail(Context c,String name){try{File f=file(c,name);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getPath(),o);o.inSampleSize=1;while(Math.max(o.outWidth,o.outHeight)/o.inSampleSize>480)o.inSampleSize*=2;o.inJustDecodeBounds=false;return BitmapFactory.decodeFile(f.getPath(),o);}catch(Exception e){return null;}}
    static String mime(String name){return name.endsWith(".png")?"image/png":name.endsWith(".webp")?"image/webp":name.endsWith(".gif")?"image/gif":"image/jpeg";}
    static JSONObject backup(Context c,ArrayList<JSONObject> posts) throws Exception {JSONObject images=new JSONObject();int total=0;for(JSONObject p:posts){String name=p.optString("image");if(name.isEmpty()||images.has(name))continue;File f=file(c,name);if(!f.exists())throw new IOException("إحدى صور الدعاية مفقودة؛ استبدلها أو أزلها قبل النسخ الاحتياطي");if(f.length()>MAX_IMAGE)throw new IOException("صورة كبيرة جدًا");byte[] bytes=java.nio.file.Files.readAllBytes(f.toPath());total+=bytes.length;if(total>MAX_BACKUP_IMAGES)throw new IOException("إجمالي صور النسخة أكبر من 12 ميغابايت؛ قلّل صور المكتبة قبل إنشاء النسخة");images.put(name,android.util.Base64.encodeToString(bytes,android.util.Base64.NO_WRAP));}return images;}
    static RestorePlan validateRestore(JSONArray posts,JSONObject images) throws Exception {RestorePlan plan=new RestorePlan();int total=0;Iterator<String> keys=images.keys();while(keys.hasNext()){String name=keys.next();if(!name.matches("[a-f0-9]{64}\\.(jpg|png|webp|gif)"))throw new IOException("اسم صورة غير صالح");String encoded=images.getString(name);if(encoded.length()>MAX_IMAGE*4/3+8)throw new IOException("صورة النسخة كبيرة جدًا");byte[] data=android.util.Base64.decode(encoded,android.util.Base64.DEFAULT);if(data.length>MAX_IMAGE)throw new IOException("صورة النسخة كبيرة جدًا");total+=data.length;if(total>MAX_BACKUP_IMAGES)throw new IOException("صور النسخة كبيرة جدًا");if(!name.equals(hash(data)+"."+extension(data)))throw new IOException("صورة النسخة غير متطابقة");plan.images.put(name,data);}for(int i=0;i<posts.length();i++){String name=posts.getJSONObject(i).optString("image");if(!name.isEmpty()&&!plan.images.containsKey(name))throw new IOException("صورة غير موجودة في النسخة الاحتياطية");}return plan;}
    static ArrayList<File> install(Context c,RestorePlan plan) throws Exception {ArrayList<File> created=new ArrayList<>();try{for(Map.Entry<String,byte[]> item:plan.images.entrySet()){File dest=file(c,item.getKey());if(dest.exists()){if(dest.length()>MAX_IMAGE||!java.util.Arrays.equals(java.nio.file.Files.readAllBytes(dest.toPath()),item.getValue()))throw new IOException("صورة محفوظة تالفة؛ أزل المنشور المرتبط بها ثم أعد المحاولة");continue;}String stored=save(c,item.getValue());if(!stored.equals(item.getKey()))throw new IOException("صورة غير صالحة");created.add(dest);}return created;}catch(Exception e){remove(created);throw e;}}
    static void remove(Collection<File> files){for(File f:files)try{if(f.isFile())f.delete();}catch(Exception ignored){}}
    static void prune(Context c,JSONArray posts){try{HashSet<String> used=new HashSet<>();for(int i=0;i<posts.length();i++){String name=posts.getJSONObject(i).optString("image");if(!name.isEmpty())used.add(name);}File dir=new File(c.getFilesDir(),"post-images");File[] files=dir.listFiles();if(files!=null)for(File f:files)if(f.isFile()&&f.getName().matches("[a-f0-9]{64}\\.(jpg|png|webp|gif)")&&!used.contains(f.getName()))f.delete();}catch(Exception ignored){}}
}
