package com.amalaei.engineering;
import android.app.*;import android.os.Bundle;import android.content.*;import android.graphics.*;import android.net.Uri;import android.widget.*;import org.json.*;import java.util.*;
@android.annotation.SuppressLint("SetTextI18n")
public final class QuoteActivity extends Activity {
 Store store;LinearLayout body,itemsBody;android.graphics.Typeface font;JSONObject draft;ArrayList<EditText[]> rows=new ArrayList<>();Map<String,EditText> fields=new LinkedHashMap<>();TextView totals;String savedSnapshot="";ArrayList<TextView> rowTitles=new ArrayList<>();
 public void onCreate(Bundle b){super.onCreate(b);if(android.os.Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(android.window.OnBackInvokedDispatcher.PRIORITY_DEFAULT,()->{if(draft==null)finish();else leave();});font=android.graphics.Typeface.createFromAsset(getAssets(),"fonts/Cairo.ttf");store=new Store(this);if(b!=null&&b.containsKey("draft"))try{draft=new JSONObject(b.getString("draft"));editor();return;}catch(Exception ignored){}String pending=getPreferences(0).getString("draft","");if(!pending.isEmpty())try{draft=new JSONObject(pending);editor();return;}catch(Exception ignored){}list();}
 protected void onPause(){if(draft!=null)try{capture();getPreferences(0).edit().putString("draft",draft.toString()).apply();}catch(Exception ignored){}super.onPause();}
 @Override public void onBackPressed(){if(draft==null){finish();return;}leave();}
 void leave(){try{capture();if(draft.toString().equals(savedSnapshot)){list();return;}}catch(Exception ignored){}new AlertDialog.Builder(this).setMessage("لديك تغييرات في عرض السعر").setPositiveButton("حفظ والعودة",(d,w)->{try{capture();store.saveQuote(draft);list();}catch(Exception e){error(e);}}).setNeutralButton("متابعة التحرير",null).setNegativeButton("تجاهل التغييرات",(d,w)->list()).show();}
 protected void onDestroy(){store.close();super.onDestroy();}protected void onSaveInstanceState(Bundle b){if(draft!=null)try{capture();b.putString("draft",draft.toString());}catch(Exception ignored){}super.onSaveInstanceState(b);}
 void base(String title){ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setLayoutDirection(android.view.View.LAYOUT_DIRECTION_RTL);body.setPadding(24,42,24,30);body.setBackgroundColor(0xfff6f7fb);scroll.addView(body);setContentView(scroll);body.setOnApplyWindowInsetsListener((v,i)->{int top,bottom;if(android.os.Build.VERSION.SDK_INT>=30){android.graphics.Insets bars=i.getInsets(android.view.WindowInsets.Type.systemBars());top=bars.top;bottom=bars.bottom;}else{top=i.getSystemWindowInsetTop();bottom=i.getSystemWindowInsetBottom();}v.setPadding(24,top+16,24,bottom+16);return i;});label(title,24);}
 TextView label(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTypeface(font);t.setTextColor(0xff303951);t.setPadding(0,10,0,10);body.addView(t);return t;}void btn(String s,Runnable r){Button b=new Button(this);b.setText(s);b.setTypeface(font);b.setTextColor(0xff5948c8);body.addView(b);b.setOnClickListener(v->r.run());}void error(Exception e){new AlertDialog.Builder(this).setMessage(e.getMessage()==null?"تعذر إتمام العملية":e.getMessage()).setPositiveButton("حسنًا",null).show();}
 EditText input(String title,String value,boolean number){label(title,13);EditText e=new EditText(this);e.setTypeface(font);e.setText(value);e.setTextSize(16);e.setInputType(number?8194:131073);body.addView(e);return e;}
 void list(){getPreferences(0).edit().remove("draft").apply();draft=null;fields.clear();rows.clear();base("عروض أسعار أجهزة المساحة");label("نموذج عروض الأسعار • ضريبة 15% • ريال سعودي",14);btn("+ إنشاء عرض سعر",()->{try{draft=new JSONObject().put("business","survey").put("number","QT-"+java.time.LocalDate.now().getYear()+"-"+String.format(java.util.Locale.US,"%04d",store.query("SELECT COALESCE(MAX(id),0)+1 AS next FROM quotes").get(0).optLong("next"))).put("date",java.time.LocalDate.now().toString()).put("customer","").put("items",new JSONArray());JSONObject profile=store.profile("survey");draft.put("company",profile.optJSONObject("quotationCompany")==null?Quotation.company():new JSONObject(profile.getJSONObject("quotationCompany").toString()));editor();}catch(Exception e){error(e);}});for(JSONObject row:store.query("SELECT * FROM quotes ORDER BY id DESC")){try{JSONObject q=new JSONObject(row.getString("data"));btn(q.optString("number")+" • "+q.optString("customer"),()->{try{draft=store.quote(row.optLong("id"));editor();}catch(Exception e){error(e);}});}catch(Exception e){error(e);}}btn("رجوع إلى العملاء",this::finish);}
 void editor(){savedSnapshot="";if(draft.optLong("id")>0)try{savedSnapshot=store.quote(draft.optLong("id")).toString();}catch(Exception ignored){}fields.clear();rows.clear();rowTitles.clear();base("عرض سعر المساحة");label("اسم العميل مطلوب. بيانات العميل الأخرى اختيارية. أسعار الوحدات قبل الضريبة؛ تُحسب 15% تلقائيًا.",14);btn("اختيار عميل محفوظ للمساحة",()->{ArrayList<JSONObject> customers=store.query("SELECT * FROM leads WHERE business='survey' ORDER BY name");String[] names=new String[customers.size()];for(int i=0;i<names.length;i++)names[i]=customers.get(i).optString("name")+" • "+customers.get(i).optString("company");new AlertDialog.Builder(this).setTitle("اختيار العميل").setItems(names,(d,n)->{JSONObject c=customers.get(n);fields.get("customer").setText(c.optString("company").isEmpty()?c.optString("name"):c.optString("company"));fields.get("customerPhone").setText(c.optString("phone"));try{JSONObject det=new JSONObject(c.optString("requestDetails","{}"));fields.get("customerVat").setText(det.optString("customerVat"));fields.get("customerAddress").setText(det.optString("customerAddress"));draft.put("leadId",c.optLong("id"));}catch(Exception ignored){}}).show();});String[][] defs={{"number","رقم العرض"},{"date","تاريخ العرض YYYY-MM-DD"},{"customer","اسم العميل / الشركة أو المنشأة *"},{"customerVat","الرقم الضريبي للعميل (اختياري)"},{"customerAddress","العنوان الوطني للعميل (اختياري)"},{"customerPhone","رقم هاتف العميل (اختياري)"}};for(String[] a:defs){EditText entry=input(a[1],draft.optString(a[0]),false);entry.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(a[0].equals("customerAddress")?110:80)});fields.put(a[0],entry);}btn("اختيار تاريخ العرض",()->{java.time.LocalDate date=java.time.LocalDate.now();new DatePickerDialog(this,(picker,y,m,d)->fields.get("date").setText(java.time.LocalDate.of(y,m+1,d).toString()),date.getYear(),date.getMonthValue()-1,date.getDayOfMonth()).show();});btn("بيانات المؤسسة في هذا النموذج",this::company);label("الأصناف",20);itemsBody=new LinearLayout(this);itemsBody.setOrientation(LinearLayout.VERTICAL);body.addView(itemsBody);totals=label("",18);btn("إضافة صنف",()->add(new JSONObject()));btn("حساب الإجماليات",()->{try{capture();summary();}catch(Exception e){error(e);}});btn("حفظ العرض",()->save(false));btn("معاينة PDF",()->export(false));btn("مشاركة PDF عبر واتساب أو البريد",()->export(true));btn("حفظ PDF في الهاتف",()->exportSave());btn("العروض المحفوظة",this::leave);JSONArray items=draft.optJSONArray("items");if(items!=null)for(int i=0;i<items.length();i++)add(items.optJSONObject(i));if(rows.isEmpty())add(new JSONObject());try{summary();}catch(Exception ignored){}}
 void add(JSONObject a){if(rows.size()>=100){Toast.makeText(this,"الحد الأقصى 100 صنف",Toast.LENGTH_SHORT).show();return;}LinearLayout prior=body;LinearLayout block=new LinearLayout(this);block.setOrientation(LinearLayout.VERTICAL);block.setPadding(12,12,12,12);itemsBody.addView(block);body=block;TextView heading=label("الصنف "+(rows.size()+1),19);rowTitles.add(heading);EditText desc=input("الوصف (حتى 80 حرفًا)",a.optString("description"),false);desc.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(80)});EditText unit=input("الوحدة",a.optString("unit","قطعة"),false),qty=input("الكمية",a.optString("qty","1"),true),price=input("سعر الوحدة قبل الضريبة",a.optString("price",""),true);unit.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(15)});EditText[] r={desc,unit,qty,price};rows.add(r);btn("حذف هذا الصنف",()->{int index=rows.indexOf(r);if(index<0)return;rows.remove(index);rowTitles.remove(index);itemsBody.removeView(block);for(int j=0;j<rowTitles.size();j++)rowTitles.get(j).setText("الصنف "+(j+1));try{capture();summary();}catch(Exception ignored){}});body=prior;for(EditText e:r)e.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int start,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){refreshTotals();}public void afterTextChanged(android.text.Editable s){}});refreshTotals();}
 void refreshTotals(){if(totals==null||draft==null)return;try{summary();}catch(Exception e){totals.setText("أكمل الكمية وسعر الوحدة لكل صنف لحساب الإجمالي");}}
 void capture()throws Exception{for(String k:fields.keySet())draft.put(k,fields.get(k).getText().toString().trim());JSONArray a=new JSONArray();for(EditText[] r:rows)a.put(new JSONObject().put("description",r[0].getText().toString()).put("unit",r[1].getText().toString()).put("qty",r[2].getText().toString()).put("price",r[3].getText().toString()));draft.put("items",a);}
 void summary()throws Exception{capture();java.math.BigDecimal sum=Quotation.subtotal(draft),tax=QuoteMath.tax(sum);totals.setText("المجموع الفرعي: "+QuoteMath.money(sum)+"\nالضريبة 15%: "+QuoteMath.money(tax)+"\nالإجمالي: "+QuoteMath.money(sum.add(tax))+" ر.س");}
 void save(boolean silent){try{capture();store.saveQuote(draft);savedSnapshot=draft.toString();getPreferences(0).edit().putString("draft",savedSnapshot).apply();summary();if(!silent)Toast.makeText(this,"حُفظ العرض",Toast.LENGTH_SHORT).show();}catch(Exception e){error(e);}}
 Uri make()throws Exception{capture();store.saveQuote(draft);savedSnapshot=draft.toString();return Uri.parse("content://"+getPackageName()+".quotes/"+Quotation.pdf(this,draft).getName());}
 void export(boolean share){try{Uri u=make();Intent i=share?new Intent(Intent.ACTION_SEND).setType("application/pdf").putExtra(Intent.EXTRA_STREAM,u).putExtra(Intent.EXTRA_SUBJECT,"عرض سعر "+draft.optString("number")):new Intent(this,QuotePreviewActivity.class).setDataAndType(u,"application/pdf");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.setClipData(ClipData.newRawUri("عرض سعر",u));if(share)startActivity(Intent.createChooser(i,"مشاركة عرض السعر"));else startActivity(i);}catch(Exception e){error(e);}}
 void exportSave(){try{Uri u=make();getPreferences(0).edit().putString("pendingPdf",u.toString()).apply();startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/pdf").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,draft.optString("number")+".pdf"),50);}catch(Exception e){error(e);}}
 protected void onActivityResult(int r,int code,Intent data){super.onActivityResult(r,code,data);if(r==50&&code==RESULT_OK&&data!=null)try(java.io.InputStream in=getContentResolver().openInputStream(Uri.parse(getPreferences(0).getString("pendingPdf","")));java.io.OutputStream out=getContentResolver().openOutputStream(data.getData())){byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);Toast.makeText(this,"حُفظ ملف PDF",Toast.LENGTH_SHORT).show();}catch(Exception e){error(e);}}
 void company(){try{capture();JSONObject c=draft.getJSONObject("company");LinearLayout prior=body;LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(20,10,20,10);body=f;Map<String,EditText> values=new LinkedHashMap<>();String[][] labels={{"name","اسم المؤسسة"},{"registration","السجل التجاري"},{"vat","الرقم الضريبي للمؤسسة"},{"address","العنوان"},{"phone","الهاتف"},{"email","البريد"}};for(String[] a:labels)values.put(a[0],input(a[1],c.optString(a[0]),false));body=prior;ScrollView scroll=new ScrollView(this);scroll.addView(f);new AlertDialog.Builder(this).setTitle("بيانات المؤسسة • المساحة فقط").setView(scroll).setNegativeButton("إلغاء",null).setPositiveButton("حفظ",(d,w)->{try{for(String k:values.keySet())c.put(k,values.get(k).getText().toString().trim());JSONObject p=store.profile("survey");p.put("quotationCompany",new JSONObject(c.toString()));if(p.optString("name").isEmpty())p.put("name",c.optString("name"));store.saveProfile("survey",p);}catch(Exception e){error(e);}}).show();}catch(Exception e){error(e);}}
}
