package com.amalaei.engineering;
import android.app.Activity;import android.os.Bundle;import android.os.ParcelFileDescriptor;import android.graphics.Bitmap;import android.graphics.Color;import android.graphics.pdf.PdfRenderer;import android.widget.*;
public final class QuotePreviewActivity extends Activity {
 private PdfRenderer renderer;private ParcelFileDescriptor descriptor;private Bitmap bitmap;private ImageView image;private TextView counter;private Button prev,next;private int page=0;
 @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setLayoutDirection(1);root.setBackgroundColor(0xffeef0f6);root.setOnApplyWindowInsetsListener((v,i)->{android.graphics.Insets bars=i.getInsets(android.view.WindowInsets.Type.systemBars());v.setPadding(12,bars.top+12,12,bars.bottom+12);return i;});setContentView(root);android.graphics.Typeface font=android.graphics.Typeface.createFromAsset(getAssets(),"fonts/Cairo.ttf");TextView title=new TextView(this);title.setText("معاينة عرض السعر");title.setTextSize(22);title.setTypeface(font);root.addView(title);ScrollView scroll=new ScrollView(this);image=new ImageView(this);image.setAdjustViewBounds(true);scroll.addView(image,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));counter=new TextView(this);counter.setTypeface(font);counter.setGravity(17);root.addView(counter);LinearLayout buttons=new LinearLayout(this);prev=new Button(this);prev.setText("السابقة");prev.setTypeface(font);next=new Button(this);next.setText("التالية");next.setTypeface(font);buttons.addView(prev,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(next,new LinearLayout.LayoutParams(0,-2,1));root.addView(buttons);Button close=new Button(this);close.setText("العودة إلى العرض");close.setTypeface(font);root.addView(close);close.setOnClickListener(v->finish());prev.setOnClickListener(v->{if(page>0){page--;render();}});next.setOnClickListener(v->{if(renderer!=null&&page+1<renderer.getPageCount()){page++;render();}});try{descriptor=getContentResolver().openFileDescriptor(getIntent().getData(),"r");if(descriptor==null)throw new java.io.IOException();renderer=new PdfRenderer(descriptor);page=state==null?0:state.getInt("page",0);page=Math.max(0,Math.min(page,renderer.getPageCount()-1));render();}catch(Exception e){counter.setText("تعذر فتح ملف PDF. ارجع إلى العرض وأعد إنشاءه.");prev.setEnabled(false);next.setEnabled(false);}}
 private void render(){if(renderer==null)return;try(PdfRenderer.Page current=renderer.openPage(page)){int width=Math.min(1800,Math.max(600,getResources().getDisplayMetrics().widthPixels));int height=Math.round(width*(float)current.getHeight()/current.getWidth());Bitmap replacement=Bitmap.createBitmap(width,height,Bitmap.Config.ARGB_8888);replacement.eraseColor(Color.WHITE);current.render(replacement,null,null,PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);Bitmap old=bitmap;bitmap=replacement;image.setImageBitmap(bitmap);if(old!=null)old.recycle();counter.setText("صفحة "+(page+1)+" من "+renderer.getPageCount());prev.setEnabled(page>0);next.setEnabled(page+1<renderer.getPageCount());}catch(Exception e){counter.setText("تعذر عرض هذه الصفحة");}}
 @Override protected void onSaveInstanceState(Bundle state){state.putInt("page",page);super.onSaveInstanceState(state);}
 @Override protected void onDestroy(){if(image!=null)image.setImageDrawable(null);if(bitmap!=null)bitmap.recycle();if(renderer!=null)renderer.close();try{if(descriptor!=null)descriptor.close();}catch(Exception ignored){}super.onDestroy();}
}
