package com.amalaei.engineering;
import org.json.*;import java.time.*;import java.math.*;
final class SoftwareWork {
 static final String[] TYPES={"subscription","development","support","training"},LABELS={"اشتراك برنامج","طلب تطوير","تذكرة دعم","عرض تجريبي / تدريب"};
 static int index(String key){for(int i=0;i<TYPES.length;i++)if(TYPES[i].equals(key))return i;return 0;}
 static String label(String key){return LABELS[index(key)];}
 static String[] statuses(String type){switch(type){case "subscription":return new String[]{"بانتظار التفعيل","نشط","بانتظار التجديد","موقوف مؤقتًا","منتهٍ / غير مجدد","ملغى"};case "development":return new String[]{"تحديد الاحتياجات","عرض وتعاقد","قيد التطوير","اختبار وتسليم","مكتمل","ملغى"};case "support":return new String[]{"جديدة","تم التواصل","قيد المعالجة","بانتظار رد العميل","تم الحل","مغلقة"};default:return new String[]{"طلب موعد","تم تحديد الموعد","بانتظار التنفيذ","متابعة بعد الجلسة","مكتمل","ملغى"};}}
 static String[][] fields(String type){switch(type){case "subscription":return new String[][]{{"program","البرنامج"},{"plan","الباقة"},{"startDate","بداية الاشتراك YYYY-MM-DD"},{"endDate","انتهاء الاشتراك YYYY-MM-DD"},{"renewDays","التنبيه قبل الانتهاء بعدد أيام"},{"amount","قيمة الاشتراك (ريال)"},{"paid","المدفوع (ريال)"},{"paymentDate","موعد الدفعة القادمة YYYY-MM-DD"},{"owner","مسؤول المتابعة"},{"notes","ملاحظات"}};case "development":return new String[][]{{"program","اسم المشروع / التطبيق"},{"platform","المنصة المطلوبة"},{"needs","الاحتياجات والمميزات المطلوبة"},{"deliveryDate","موعد التسليم YYYY-MM-DD"},{"amount","قيمة الاتفاق (ريال)"},{"paid","المدفوع (ريال)"},{"paymentDate","موعد الدفعة القادمة YYYY-MM-DD"},{"owner","مسؤول التطوير"},{"notes","ملاحظات"}};case "support":return new String[][]{{"program","البرنامج"},{"issue","وصف المشكلة"},{"owner","مسؤول الدعم"},{"resolution","الإجراءات والنتيجة"},{"notes","ملاحظات"}};default:return new String[][]{{"program","البرنامج"},{"sessionDate","تاريخ الجلسة YYYY-MM-DD"},{"sessionTime","وقت الجلسة HH:mm"},{"owner","المسؤول"},{"needs","موضوع الجلسة"},{"resolution","النتيجة وخطوة المتابعة"},{"notes","ملاحظات"}};}}
 static BigDecimal value(String s){if(s.trim().isEmpty())return BigDecimal.ZERO;return QuoteMath.number(s);}
 static void validate(JSONObject q)throws Exception{if(q.optString("title").trim().isEmpty())throw new IllegalArgumentException("أدخل عنوان الطلب");boolean valid=false;for(String t:TYPES)if(t.equals(q.optString("type")))valid=true;if(!valid||q.optInt("status")<0||q.optInt("status")>5||q.optInt("priority",1)<0||q.optInt("priority",1)>3)throw new IllegalArgumentException("نوع أو حالة غير صالحة");JSONObject d=q.getJSONObject("details");for(String k:new String[]{"startDate","endDate","deliveryDate","paymentDate","sessionDate"})if(!d.optString(k).isEmpty())LocalDate.parse(d.getString(k));if(!d.optString("sessionTime").isEmpty())LocalTime.parse(d.getString("sessionTime"));if(!d.optString("startDate").isEmpty()&&!d.optString("endDate").isEmpty()&&d.getString("startDate").compareTo(d.getString("endDate"))>0)throw new IllegalArgumentException("انتهاء الاشتراك قبل بدايته");if(!d.optString("renewDays").isEmpty()){int n=Integer.parseInt(d.getString("renewDays"));if(n<0||n>365)throw new IllegalArgumentException("مدة التنبيه من صفر إلى 365 يومًا");}if(value(d.optString("paid")).compareTo(value(d.optString("amount")))>0)throw new IllegalArgumentException("المدفوع أكبر من قيمة الاتفاق");if(!q.optString("followUp").isEmpty())LocalDate.parse(q.getString("followUp"));LocalTime.parse(q.optString("followTime","09:00"));}
 static String due(JSONObject q,String kind){if(q.optInt("status")>=4)return "";JSONObject d=q.optJSONObject("details");if(d==null)return "";try{if(kind.equals("follow"))return q.optString("followUp");if(kind.equals("renew")&&q.optString("type").equals("subscription")&&!d.optString("endDate").isEmpty())return LocalDate.parse(d.getString("endDate")).minusDays(Integer.parseInt(d.optString("renewDays","7").isEmpty()?"7":d.optString("renewDays","7"))).toString();if(kind.equals("payment")&&value(d.optString("amount")).compareTo(value(d.optString("paid")))>0)return d.optString("paymentDate");if(kind.equals("delivery")&&q.optString("type").equals("development"))return d.optString("deliveryDate");if(kind.equals("session")&&q.optString("type").equals("training"))return d.optString("sessionDate");}catch(Exception ignored){}return "";}
 static String time(JSONObject q,String kind){JSONObject d=q.optJSONObject("details");return kind.equals("session")&&d!=null&&!d.optString("sessionTime").isEmpty()?d.optString("sessionTime"):q.optString("followTime","09:00");}
 static String reminderLabel(String k){switch(k){case "renew":return "تجديد الاشتراك";case "payment":return "الدفعة المستحقة";case "delivery":return "تسليم المشروع";case "session":return "موعد الجلسة";default:return "متابعة الطلب";}}
 static final String[] REMINDERS={"follow","renew","payment","delivery","session"};
}
