package com.amalaei.engineering;
final class SurveyRequests {
 static final String[] KEYS={"sales","support","maintenance","calibration"};
 static final String[] LABELS={"مبيعات أجهزة المساحة","دعم فني","صيانة أجهزة","معايرة أجهزة"};
 static int index(String key){for(int i=0;i<KEYS.length;i++)if(KEYS[i].equals(key))return i;return 0;}
 static boolean valid(String key){for(String k:KEYS)if(k.equals(key))return true;return false;}
 static String label(String key){return LABELS[index(key)];}
 static String[] stages(String business,String key){if("software".equals(business))return new String[]{"استفسار جديد","تحديد الاحتياجات","عرض تجريبي","عرض اشتراك أو تطوير","تم التعاقد","فقدت الفرصة"};switch(key){case "support":return new String[]{"طلب دعم جديد","تم التواصل","قيد التشخيص","بانتظار رد العميل","تم حل المشكلة","أُغلق دون حل"};case "maintenance":return new String[]{"طلب صيانة جديد","تم استلام الجهاز","فحص وتشخيص","قيد الصيانة","تم التسليم","أُلغي الطلب"};case "calibration":return new String[]{"طلب معايرة جديد","تم استلام الجهاز","قيد المعايرة","جاهز للتسليم","تم التسليم","أُلغي الطلب"};default:return new String[]{"جديد","تم التواصل","مؤهل للشراء","عرض مقدم","تم البيع","فقدت الفرصة"};}}
 static String[][] fields(String key){switch(key){case "support":return new String[][]{{"device","نوع الجهاز"},{"model","الموديل"},{"serialNumber","الرقم التسلسلي"},{"issue","وصف المشكلة / طلب الدعم"},{"technician","مسؤول الدعم"},{"workDone","الإجراءات المنفذة / نتيجة الدعم"}};case "maintenance":return new String[][]{{"device","نوع الجهاز"},{"model","الموديل"},{"serialNumber","الرقم التسلسلي"},{"issue","وصف العطل"},{"receivedDate","تاريخ استلام الجهاز (YYYY-MM-DD)"},{"deliveryDate","موعد التسليم المتوقع (YYYY-MM-DD)"},{"technician","الفني المسؤول"},{"budget","التكلفة المتوقعة (ريال)"},{"warranty","حالة الضمان"},{"workDone","أعمال الصيانة المنفذة"}};case "calibration":return new String[][]{{"device","نوع الجهاز"},{"model","الموديل"},{"serialNumber","الرقم التسلسلي"},{"receivedDate","تاريخ استلام الجهاز (YYYY-MM-DD)"},{"deliveryDate","موعد التسليم المتوقع (YYYY-MM-DD)"},{"technician","مسؤول المعايرة"},{"certificate","رقم شهادة المعايرة"},{"calibrationDate","موعد تجديد المعايرة (YYYY-MM-DD)"},{"workDone","نتيجة المعايرة"}};default:return new String[][]{{"device","نوع الجهاز"},{"model","الموديل"},{"service","الخدمة: بيع / تأجير"},{"condition","الحالة: جديد / مستعمل"},{"quantity","الكمية"},{"budget","الميزانية المتوقعة (ريال)"},{"purchaseDate","موعد الشراء المتوقع (YYYY-MM-DD)"},{"calibrationDate","موعد تجديد المعايرة (YYYY-MM-DD)"}};}}
 static String[] combined(){return new String[]{"طلبات جديدة","تم التواصل أو الاستلام","تقييم وتشخيص","قيد الإجراء","طلبات مكتملة","طلبات مغلقة"};}
}
